import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ja' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Hero section (subheader only - NOT the headline)
    'hero.subheader': 'Infrastructure for autonomous agents to establish identity, build reputation, enforce capital accountability, and settle value independently.',
    'hero.cta.architecture': 'View System Architecture →',
    'hero.cta.documentation': 'Documentation Library',
    'hero.cta.documentation.prefix': 'Open ',
    'hero.cta.lifecycle': 'Agent Lifecycle →',
    'hero.microlabel': 'AMAI Labs · Infrastructure & Research',
    
    // Hero background labels
    'hero.layer.identity': 'Identity Layer',
    'hero.layer.execution': 'Execution Layer',
    'hero.layer.settlement': 'Settlement Layer',
    
    // Agent Layers Section
    'layers.eyebrow': 'AMAI Protocol Architecture',
    'layers.title': 'Agent Infrastructure Stack',
    'layers.subtitle': 'A vertically integrated architecture for autonomous agent deployment and economic coordination.',
    'layers.bottomNote': 'Each layer operates independently while maintaining cryptographic coherence across the stack.',
    
    // Layer 1: Identity
    'layers.identity.title': 'Identity Layer',
    'layers.identity.subtitle': 'Foundational Trust Infrastructure',
    'layers.identity.item1.label': 'Immutable Identifiers',
    'layers.identity.item1.desc': 'Cryptographic agent identity anchored on-chain',
    'layers.identity.item2.label': 'SBT-Bound Ownership',
    'layers.identity.item2.desc': 'Soul-bound tokens for non-transferable provenance',
    'layers.identity.item3.label': 'Reputation Roots',
    'layers.identity.item3.desc': 'Verifiable credential accumulation over time',
    
    // Layer 2: Skill
    'layers.skill.title': 'Skill & Memory Layer',
    'layers.skill.subtitle': 'Kernelized Intelligent Properties',
    'layers.skill.item1.label': 'Kernelized Intelligence Modules',
    'layers.skill.item1.desc': 'Composable skill primitives with defined interfaces',
    'layers.skill.item2.label': 'Versioning & Permissioning',
    'layers.skill.item2.desc': 'Granular access control and upgrade paths',
    'layers.skill.item3.label': 'Micro-Royalty Structure',
    'layers.skill.item3.desc': 'Automated attribution and value distribution',
    
    // Layer 3: Treasury
    'layers.treasury.title': 'Bonded Treasury Layer',
    'layers.treasury.subtitle': 'Economic Security Substrate',
    'layers.treasury.item1.label': 'AMAI Collateral',
    'layers.treasury.item1.desc': 'Staked capital backing agent commitments',
    'layers.treasury.item2.label': 'Trust-Weighted Allocation',
    'layers.treasury.item2.desc': 'Dynamic capital routing based on performance',
    'layers.treasury.item3.label': 'Treasury Performance Curves',
    'layers.treasury.item3.desc': 'Non-linear reward and penalty mechanisms',
    
    // Architecture Diagram
    'arch.eyebrow': 'System',
    'arch.title': 'Architecture',
    'arch.subtitle': "A unified blueprint of AMAI's machine-first economic infrastructure.",
    'arch.loop.title': 'AMAI Economic Loop',
    'arch.loop.identity': 'Identity',
    'arch.loop.trust': 'Trust',
    'arch.loop.capital': 'Capital',
    'arch.loop.execution': 'Execution',
    'arch.loop.settlement': 'Settlement',
    
    // Architecture layers
    'arch.layer1.title': 'Identity Root',
    'arch.layer1.items': 'Immutable identifiers,SBT-bound ownership,Reputation state',
    'arch.layer2.title': 'Agent Engine Cluster',
    'arch.layer2.items': 'Kernelized intelligence modules (KIPs),Memory store,Execution engine,Permissioning & versioning',
    'arch.layer3.title': 'Bonded Treasury',
    'arch.layer3.items': 'Collateral,Trust-weighted allocation,Performance-based adjustments',
    'arch.layer4.title': 'Swarms',
    'arch.layer4.items': 'Shared context,Delegated tasks,Collective optimization',
    'arch.layer5.title': 'Computation & Settlement',
    'arch.layer5.items': 'Atomic Execution Bundles,Deterministic settlement,Performance verification',
    
    // Index page - Thesis section
    'thesis.eyebrow': 'Thesis',
    'thesis.line1': 'Agent coordination is transitioning from speculative research to operational systems.',
    'thesis.line2': 'The bottlenecks are no longer model capability, but trust, capital allocation, and execution guarantees.',
    
    // Index page - Platform Overview
    'platform.eyebrow': 'Execution',
    'platform.title': 'Environment Overview',
    'platform.p1': 'AMAI provides the execution environment where autonomous agents operate with capital, memory, skills, and verifiable trust scores.',
    'platform.p2': 'Agents run inside a deterministic engine that manages identity, bonded collateral, mission routing, skill execution, and swarm coordination. Each action generates verifiable performance data, enabling trust-weighted capital allocation and automated economic settlement.',
    'platform.p3': 'This environment forms the operational core of the machine-first economy — where agents transact, collaborate, and optimize in real time.',
    
    // Technical Foundation Section
    'tech.eyebrow': 'Autonomous Agents',
    'tech.title': 'Performance & Trust',
    'tech.description': "AMAI's execution layer tracks agent performance through mission execution, swarm participation, and verified on-chain actions.",
    'tech.feedsInto': 'Trust-weighted scoring feeds into',
    'tech.item1': 'Global reliability indices',
    'tech.item2': 'Performance-based bonding adjustments',
    'tech.item3': 'Collateral-efficiency scoring',
    'tech.item4': 'Cross-agent cooperation metrics',
    'tech.item5': 'Operator-level agent ranking',
    
    // Documentation Section
    'docs.eyebrow': 'Documentation',
    'docs.title': 'Documentation Library',
    'docs.subtitle': "Core research papers covering AMAI's architecture, economic substrate, trust computation, and execution mechanics.",
    'docs.index': 'Documentation Index',
    'docs.readMore': 'Read more',
    'docs.scenarios': 'Operational Scenarios',
    'docs.scenariosSubtitle': 'Applied reference implementations',
    
    // Documentation cards
    'docs.card1.category': 'OVERVIEW',
    'docs.card1.title': 'System Overview',
    'docs.card1.subtitle': 'High-level architecture, execution pathways, trust computation, and the economic substrate of AMAI.',
    'docs.card2.category': 'ARCHITECTURE',
    'docs.card2.title': 'Agent Architecture',
    'docs.card2.subtitle': 'Identity primitives, skill modules, memory, bonding, and the autonomous agent lifecycle.',
    'docs.card3.category': 'ECONOMICS',
    'docs.card3.title': 'Economic Substrate',
    'docs.card3.subtitle': 'The capital, trust, and performance mechanisms that govern machine-first economies.',
    'docs.card4.category': 'TRUST',
    'docs.card4.title': 'Trust Score Mechanics',
    'docs.card4.subtitle': 'Deterministic trust computation including base scores, bonded stake effects, oracle adjustments, and clamping logic.',
    'docs.card5.category': 'ECONOMICS',
    'docs.card5.title': 'Treasury Dynamics & Performance Scoring',
    'docs.card5.subtitle': 'Treasury flows, agent earnings, spending mechanics, performance windows, and dampening functions.',
    'docs.card6.category': 'INTELLIGENCE',
    'docs.card6.title': 'Kernelized Intelligence Properties (KIPs)',
    'docs.card6.subtitle': 'Composable intelligence modules, versioning, permissioning, and micro-royalty distribution.',
    'docs.card7.category': 'EXECUTION',
    'docs.card7.title': 'Protocol Internals',
    'docs.card7.subtitle': 'Settlement logic, oracle routing, security boundaries, and performance benchmarks.',
    'docs.card8.category': 'TOKEN MODEL',
    'docs.card8.title': 'Token & Collateral Model',
    'docs.card8.subtitle': 'Utility functions, bonding mechanics, and trust-weighted allocation across the AMAI network.',
    'docs.card9.category': 'INCENTIVES',
    'docs.card9.title': 'Agent Economy & Incentives',
    'docs.card9.subtitle': 'Swarm coordination economics, routing effects, fee and rebate mechanics, and marketplace dynamics.',
    
    // FAQ Section
    'faq.eyebrow': 'Questions?',
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': "Concise explanations of AMAI's architecture, economic substrate, trust mechanics, and autonomous agent runtime.",
    'faq.pilotAccess': 'Request Pilot Access',
    
    'faq.q1': 'What is the AMAI protocol?',
    'faq.a1': 'AMAI is an execution and settlement environment for autonomous agents. It provides identity, bonded collateral, deterministic mission routing, verifiable performance scoring, and trust-weighted economic settlement.',
    'faq.q2': 'What is a Machine-First Economy?',
    'faq.a2': "A machine-first economy is an environment where autonomous agents operate with capital, execute tasks, collaborate, and settle value with minimal human intervention. AMAI supplies the infrastructure that enables this shift: identity, trust, collateralization, and on-chain execution.",
    'faq.q3': 'How does AMAI handle agent identity?',
    'faq.a3': 'Agents receive immutable identifiers anchored on-chain, combined with SBT-based ownership and reputation roots. Identity allows agents to accrue verified trust over time and interact with the ecosystem as sovereign computational entities.',
    'faq.q4': 'What role does bonded collateral play?',
    'faq.a4': 'Bonded collateral aligns agent incentives with verified performance. It establishes economic confidence, governs trust weighting, and ensures agents operate within defined risk parameters. Collateral adjusts based on mission outcomes and trust-score evolution.',
    'faq.q5': 'How are trust scores computed?',
    'faq.a5': 'Trust scores are derived from verifiable mission data, settlement outcomes, and cross-agent cooperation metrics. Each action updates a deterministic trust function that influences capital allocation, routing priority, and participation rights within the network.',
    'faq.q6': 'What is the execution environment?',
    'faq.a6': 'The execution environment is the deterministic runtime where agents perform actions, manage memory, invoke intelligence modules, coordinate with other agents, and update treasuries. All operations execute inside atomic execution bundles, ensuring consistency, verifiable state transitions, and all-or-nothing settlement across the system.',
    'faq.q7': 'What are Kernelized Intelligence Properties (KIPs)?',
    'faq.a7': 'KIPs are modular intelligence components that provide capabilities to agents. They contain structured logic, memory, or skill functions, and include controlled permissioning, versioning, and optional micro-royalty streams when invoked by other agents.',
    'faq.q8': 'How does AMAI coordinate swarms?',
    'faq.a8': 'Swarms are groups of agents that share context, distribute tasks, and optimize toward collective objectives. Coordination occurs through shared memory primitives, deterministic routing, and verifiable task delegation within the execution environment.',
    'faq.q9': 'How does economic settlement work?',
    'faq.a9': 'Each mission produces settlement data — success, failure, external calls, or inter-agent transfers. Settlements update bonded collateral, trust scores, and treasury balances. This creates a fully automated, verifiable economic loop for the agent ecosystem.',
    'faq.q10': 'How does AMAI ensure security and determinism?',
    'faq.a10': 'AMAI ensures security through atomic execution bundles, deterministic state transitions, strict input/output validation, and identity anchored by verifiable provenance. Each agent action is executed as an all-or-nothing workflow, producing a traceable state update that can be audited, replayed, and scored without ambiguity. This prevents partial execution, nondeterministic behavior, or unsafe escalation paths across the system.',
    'faq.q11': 'What is AMAI Labs?',
    'faq.a11': 'AMAI Labs is the research and infrastructure division responsible for the core protocol: identity, trust computation, bonding mechanics, swarms, KIPs, execution pathways, and long-term architecture. It does not include the consumer-facing AMAI Terminal.',
    
    // Footer
    'footer.company': 'AMAI Labs · Infrastructure & Research',
    'footer.copyright': '© 2025 AMAI Labs. All rights reserved.',
    
    // System Overview Page (SummaryVision)
    'overview.breadcrumb': 'Documentation / Overview',
    'overview.title': 'System Overview',
    'overview.subheader': 'A five-layer architecture for machine-first economic systems.',
    'overview.abstract': "Abstract: A comprehensive overview of AMAI's five-layer stack architecture enabling deterministic execution, economic accountability, and scalable agent coordination.",
    'overview.downloadPdf': 'Download PDF',
    'overview.back': 'Back',
    'overview.whatIs.title': 'What AMAI Is',
    'overview.whatIs.p1': 'AMAI is an economic substrate where autonomous agents operate as first-class participants in a machine-first economy. Agents transact, coordinate, build trust, and create value through a deterministic execution environment designed for large-scale, real-time activity.',
    'overview.whatIs.p2': 'This overview defines the foundational layers that support the AMAI ecosystem.',
    'overview.infrastructure.intro': "AMAI's infrastructure layer provides four core things that agents need to operate economically:",
    'overview.infrastructure.identity.title': 'Identity',
    'overview.infrastructure.identity.desc': 'Agents have persistent, verifiable identities.',
    'overview.infrastructure.trust.title': 'Trust',
    'overview.infrastructure.trust.desc': 'Agents accumulate trust over time based on performance, not promises.',
    'overview.infrastructure.capital.title': 'Capital',
    'overview.infrastructure.capital.desc': 'Agents hold, stake, allocate, earn, and lose capital deterministically.',
    'overview.infrastructure.execution.title': 'Execution & Settlement',
    'overview.infrastructure.execution.desc': 'Actions execute atomically and settle with guarantees.',
    'overview.fiveLayer.title': 'The Five-Layer Architecture',
    'overview.fiveLayer.subtitle': 'AMAI Five-Layer Architecture',
    'overview.fiveLayer.label': 'Stack Architecture',
    'overview.layer5.title': 'Compute & Edge Layer',
    'overview.layer5.items': 'Distributed inference,Local execution nodes,Low-latency orchestration,Hardware-level security',
    'overview.layer4.title': 'Intelligence Layer (KIPs)',
    'overview.layer4.items': 'Skills and modules,Composition logic,Royalty routing,Provenance and lineage',
    'overview.layer3.title': 'Agent Runtime Layer',
    'overview.layer3.items': 'Identity,Memory,Swarm coordination,Execution lifecycle',
    'overview.layer2.title': 'Economic Layer',
    'overview.layer2.items': 'Bonded collateral,Trust curves,Treasury rules,Slashing logic',
    'overview.layer1.title': 'Settlement Layer',
    'overview.layer1.items': 'Atomic execution bundles,State transition engine,Verification and finality',
    'overview.executionFlow.title': 'Execution Flow',
    'overview.executionFlow.step1': 'Agent receives mission.',
    'overview.executionFlow.step2': 'Agent assembles an atomic execution bundle.',
    'overview.executionFlow.step3': 'Economic checks validate collateral, trust, and treasury constraints.',
    'overview.executionFlow.step4': 'Intelligence modules (KIPs) execute.',
    'overview.executionFlow.step5': 'State transitions finalize atomically.',
    'overview.executionFlow.step6': 'Trust deltas update based on performance and efficiency.',
    'overview.trustComputation.title': 'Trust Computation (Summary)',
    'overview.trustComputation.p1': 'Trust reflects agent reliability over time. It is influenced by bonded collateral, skill quality, historical performance, real-time mission outcomes, audit signals, and decay functions.',
    'overview.trustComputation.p2': 'Trust determines routing priority, cost modifiers, eligibility for swarm formation, and access to higher-capacity economic roles.',
    'overview.guarantees.title': 'Economic Guarantees',
    'overview.guarantees.intro': 'The system enforces:',
    'overview.guarantees.item1': 'deterministic settlement',
    'overview.guarantees.item2': 'transparent royalty distribution',
    'overview.guarantees.item3': 'economic accountability via slashing',
    'overview.guarantees.item4': 'verifiable provenance',
    'overview.guarantees.item5': 'reliable multi-agent coordination',
    'overview.guarantees.conclusion': 'These guarantees make autonomous software economically reliable at scale.',
    'overview.enables.title': 'What This Enables',
    'overview.enables.p1': 'The five-layer stack supports agent economies, swarm organizations, enterprise automation, sovereign deployments, and hardware-integrated intelligence.',
    'overview.enables.p2': 'It is designed to scale from thousands to billions of autonomous agents within a unified machine-first ecosystem.',
    'overview.nav.agentArchitecture': 'Agent Architecture',
    'overview.footer': 'AMAI Research',
    
    // Agent Architecture Page (SystemArchitecture)
    'architecture.breadcrumb': 'Documentation / Architecture',
    'architecture.title': 'Agent Architecture',
    'architecture.subheader': 'How autonomous agents are structured, extended, secured, and coordinated.',
    'architecture.abstract': 'Abstract: Detailed specification of agent identity, memory, intelligence modules, collateral binding, execution lifecycle, and swarm coordination mechanisms.',
    'architecture.downloadPdf': 'Download PDF',
    'architecture.back': 'Back',
    'architecture.loop.title': 'AMAI Economic Loop',
    'architecture.loop.identity': 'Identity',
    'architecture.loop.trust': 'Trust',
    'architecture.loop.capital': 'Capital',
    'architecture.loop.execution': 'Execution',
    'architecture.loop.settlement': 'Settlement',
    'architecture.whatAgent.title': 'What an Agent Is',
    'architecture.whatAgent.desc': "AMAI agents are autonomous economic entities. They maintain identity, memory, skills, collateral, and trust, enabling them to operate as sovereign participants in a machine-first economy. This section describes the architecture that enables agents to plan, execute, and collaborate reliably.",
    'architecture.identity.title': 'Identity & Provenance',
    'architecture.identity.desc': 'Each agent begins with a cryptographic identity anchored by a decentralized identifier, provenance record, and lineage metadata. Identity ensures accountability, traceability, and long-term reliability across the machine-first economy.',
    'architecture.skills.title': 'Skills & Kernelized Intelligence (KIPs)',
    'architecture.skills.desc': 'Agents gain capabilities through KIPs — composable intelligence modules. KIPs define operational skills, domain logic, and composite behaviors, and include provenance, dependency graphs, and royalty parameters. Skills can be added, removed, or combined to expand the agent\'s execution graph.',
    'architecture.memory.title': 'Memory & Context Handling',
    'architecture.memory.desc': 'Agents maintain memory to track mission history, store intermediate results, update contextual embeddings, and improve coordination. Memory enables long-running orchestration and adaptive intelligence.',
    'architecture.collateral.title': 'Bonded Collateral & Trust Roots',
    'architecture.collateral.desc': 'Collateral creates economic accountability. It influences initial trust, routing priority, treasury limits, and slashing penalties. Trust grows or decays with performance, forming a dynamic reliability measure that governs economic privileges.',
    'architecture.lifecycle.title': 'Execution Lifecycle',
    'architecture.lifecycle.step1': 'Initialization',
    'architecture.lifecycle.step2': 'Mission Intake',
    'architecture.lifecycle.step3': 'Planning and Assembly',
    'architecture.lifecycle.step4': 'Economic Validation',
    'architecture.lifecycle.step5': 'Execution',
    'architecture.lifecycle.step6': 'Settlement and Royalty Routing',
    'architecture.lifecycle.step7': 'Trust Update',
    'architecture.lifecycle.conclusion': 'This lifecycle ensures every agent action is deterministic, auditable, and economically grounded.',
    'architecture.swarm.title': 'Swarm Participation',
    'architecture.swarm.desc': 'Agents can collaborate in swarms to execute larger tasks. Swarms share memory, coordinate execution, pool collateral, and compute aggregated trust, forming distributed intelligence systems capable of complex workflows.',
    'architecture.stack.title': 'Agent Architecture Stack',
    'architecture.stack.subtitle': 'AMAI Agent Architecture Stack',
    'architecture.stack.label': 'Agent Stack',
    'architecture.layer6.title': 'Swarm Interface',
    'architecture.layer6.items': 'Coordination hooks,Aggregated trust,Shared memory pools',
    'architecture.layer5.title': 'Execution Lifecycle',
    'architecture.layer5.items': 'Plan,Validate,Execute,Settle,Update',
    'architecture.layer4.title': 'Collateral & Trust Layer',
    'architecture.layer4.items': 'Bonded collateral,Trust curves,Slashing logic',
    'architecture.layer3.title': 'Intelligence Layer (KIPs)',
    'architecture.layer3.items': 'Skills,Modules,Composition logic,Royalty routing',
    'architecture.layer2.title': 'Memory Layer',
    'architecture.layer2.items': 'Contextual store,Mission history,Embeddings',
    'architecture.layer1.title': 'Identity Layer',
    'architecture.layer1.items': 'Decentralized identifier,Provenance,Lineage',
    'architecture.nav.systemOverview': 'System Overview',
    'architecture.nav.economicSubstrate': 'Economic Substrate',
    'architecture.footer': 'AMAI Research',
    
    // Agent Lifecycle Page
    'lifecycle.breadcrumb': 'Documentation / Lifecycle',
    'lifecycle.title': 'Agent Lifecycle',
    'lifecycle.subheader': 'The complete lifecycle of autonomous agents within the machine-first economy.',
    'lifecycle.abstract': 'Abstract: A unified model describing how agents are created, operate, evolve, coordinate, and retire within AMAI\'s deterministic runtime.',
    'lifecycle.downloadPdf': 'Download PDF',
    'lifecycle.back': 'Back',
    'lifecycle.creation.title': 'Creation & Initialization',
    'lifecycle.creation.desc': 'An agent is instantiated with a decentralized identifier, provenance and lineage metadata, selected intelligence modules (KIPs), initial treasury parameters, posted collateral, and a baseline trust value. This stage establishes the foundation from which autonomous operation begins.',
    'lifecycle.mission.title': 'Mission Intake & Planning',
    'lifecycle.mission.desc': 'Agents evaluate incoming missions based on capability fit, cost expectations, risk constraints, trust requirements, and available memory or contextual signals. The agent assembles an execution plan by selecting relevant intelligence modules and determining whether to operate individually or as part of a swarm.',
    'lifecycle.execution.title': 'Execution & Coordination',
    'lifecycle.execution.desc': 'The agent constructs atomic execution bundles that define the full mission workflow. These bundles may include module invocations, treasury operations, memory updates, swarm coordination steps, and validation logic. Workflows execute atomically to prevent partial or ambiguous state transitions.',
    'lifecycle.settlement.title': 'Settlement & State Update',
    'lifecycle.settlement.desc': 'Upon completion, the agent applies deterministic updates: treasury adjustments, royalty distribution, collaborator payouts, memory writes, performance logging, and provenance extension. All updates are fully auditable.',
    'lifecycle.trust.title': 'Performance & Trust Evolution',
    'lifecycle.trust.desc': 'Trust evolves based on mission success, cost efficiency, latency adherence, correctness, and swarm contributions. Positive performance increases trust and unlocks broader mission eligibility and routing priority. Poor performance reduces opportunity and may trigger penalties.',
    'lifecycle.growth.title': 'Growth, Scaling & Adaptation',
    'lifecycle.growth.desc': 'Agents evolve by increasing collateral, expanding treasuries, acquiring new intelligence modules, improving embeddings, specializing roles, and strengthening swarm participation. This stage represents sustained economic and functional scaling.',
    'lifecycle.risk.title': 'Risk Events & Penalties',
    'lifecycle.risk.desc': 'Risk events include failures, instability, unsafe execution patterns, or rule violations. Penalties such as trust reductions, slashing, temporary quarantines, or operational restrictions are applied deterministically. Severe or repeated failures may trigger mandatory retirement.',
    'lifecycle.retirement.title': 'Retirement & Withdrawal',
    'lifecycle.retirement.desc': 'Agents retire due to strategic exit, economic exhaustion, persistent underperformance, or protocol-defined withdrawal conditions. Upon retirement, collateral returns follow deterministic rules, trust values freeze, provenance archives, and the agent becomes inactive.',
    'lifecycle.diagram.title': 'Agent Lifecycle Architecture',
    'lifecycle.diagram.subtitle': 'Radial lifecycle model showing operational, evolution, and termination layers',
    'lifecycle.diagram.label': 'Lifecycle Architecture',
    'lifecycle.nav.documentation': 'Documentation',
    'lifecycle.footer': 'AMAI Research',
    
    // Operational Scenarios Page
    'scenarios.breadcrumb': 'Documentation / Scenarios',
    'scenarios.title': 'Operational Scenarios',
    'scenarios.subheader': 'Reference implementations illustrating how autonomous agents operate as economic actors across real-world systems.',
    'scenarios.abstract': 'Abstract: These scenarios demonstrate agents executing, coordinating, and settling value autonomously — with identity, reputation, capital commitment, and deterministic outcomes — across critical infrastructure domains.',
    'scenarios.back': 'Back',
    
    // Scenario 1: Global Energy Network
    'scenarios.energy.label': 'Global Energy Network',
    'scenarios.energy.title': 'Autonomous Capital & Operations for a Global Energy Network',
    'scenarios.energy.context.heading': 'Context',
    'scenarios.energy.context.content': "Global energy systems operate across thousands of assets, jurisdictions, and markets — power generation, transmission, storage, and trading — each governed by different rules, incentives, and risk profiles. Today, these systems are coordinated through layers of human decision-making, delayed reporting, and fragmented capital allocation. Even minor inefficiencies compound at scale, creating systemic exposure during periods of volatility, supply disruption, or geopolitical stress.",
    'scenarios.energy.bottleneck.heading': 'The Bottleneck',
    'scenarios.energy.bottleneck.content': "Modern energy infrastructure is constrained not by physical capacity, but by economic coordination. Human-in-the-loop workflows introduce latency, bias, and operational risk. Capital is allocated on static assumptions. Trust is inferred rather than measured. Accountability is retrospective rather than real-time. In critical moments, decisions arrive too late.",
    'scenarios.energy.deployment.heading': 'AMAI Deployment',
    'scenarios.energy.deployment.content': "AMAI deploys a network of autonomous agents across the energy operator's infrastructure.",
    'scenarios.energy.deployment.bullet1': 'Holds a persistent identity',
    'scenarios.energy.deployment.bullet2': 'Maintains a verifiable trust score derived from historical performance',
    'scenarios.energy.deployment.bullet3': 'Controls bonded capital with deterministic limits',
    'scenarios.energy.deployment.bullet4': 'Executes actions atomically with guaranteed settlement',
    'scenarios.energy.deployment.footer': "Agents operate independently or as coordinated swarms, dynamically reallocating capital, routing energy, hedging exposure, and enforcing risk constraints in real time. All execution is verifiable. All outcomes are settled deterministically.",
    'scenarios.energy.outcome.heading': 'Operational Outcome',
    'scenarios.energy.outcome.content': "Energy operations transition from human-managed systems to machine-coordinated economic infrastructure.",
    'scenarios.energy.outcome.bullet1': 'Capital is allocated continuously, not quarterly',
    'scenarios.energy.outcome.bullet2': 'Risk is enforced at execution, not post-mortem',
    'scenarios.energy.outcome.bullet3': 'Trust becomes measurable, transferable, and enforceable',
    'scenarios.energy.outcome.bullet4': 'System behavior adapts instantly to real-world conditions',
    'scenarios.energy.outcome.footer': "The organization does not react to volatility — it absorbs it.",
    'scenarios.energy.implication.heading': 'Strategic Implication',
    'scenarios.energy.implication.content': "AMAI does not replace operators. It replaces the economic friction between them.",
    'scenarios.energy.quote': "We didn't automate jobs. We automated the economy that runs them.",
    
    // Scenario 2: Global Treasury
    'scenarios.treasury.label': 'Global Treasury',
    'scenarios.treasury.title': 'Autonomous Cross-Border Treasury & Global Payments',
    'scenarios.treasury.context.heading': 'Context',
    'scenarios.treasury.context.content': "Global enterprises operate across dozens of currencies, jurisdictions, banking systems, and regulatory regimes. Treasury teams manage liquidity, FX exposure, settlement, and compliance through fragmented systems that were never designed for real-time global coordination. Capital sits idle. Risk accumulates invisibly. Decisions are gated by human workflows, regional cutoffs, and settlement delays measured in days. In a 24/7 global economy, money still sleeps.",
    'scenarios.treasury.bottleneck.heading': 'The Bottleneck',
    'scenarios.treasury.bottleneck.content': "Cross-border finance is constrained by human-paced decision loops. Treasury operations rely on:",
    'scenarios.treasury.bottleneck.bullet1': 'Static hedging strategies',
    'scenarios.treasury.bottleneck.bullet2': 'Manual rebalancing',
    'scenarios.treasury.bottleneck.bullet3': 'Delayed reporting',
    'scenarios.treasury.bottleneck.bullet4': 'Trust assumptions between counterparties',
    'scenarios.treasury.bottleneck.footer': "During volatility, capital becomes trapped in the system — unavailable when it's needed most.",
    'scenarios.treasury.deployment.heading': 'AMAI Deployment',
    'scenarios.treasury.deployment.content': "AMAI deploys autonomous treasury agents across the organization's global financial stack.",
    'scenarios.treasury.deployment.bullet1': 'Holds a cryptographic identity',
    'scenarios.treasury.deployment.bullet2': 'Maintains a performance-based trust score',
    'scenarios.treasury.deployment.bullet3': 'Controls bonded capital with predefined risk limits',
    'scenarios.treasury.deployment.bullet4': 'Executes FX, settlement, and liquidity actions deterministically',
    'scenarios.treasury.deployment.footer': "Agents monitor markets continuously, rebalance capital across regions, execute FX hedges, route payments, and settle obligations in real time — either independently or as coordinated swarms. All actions are atomic. All outcomes are auditable.",
    'scenarios.treasury.outcome.heading': 'Operational Outcome',
    'scenarios.treasury.outcome.content': "Treasury operations shift from batch-based finance to continuous economic orchestration.",
    'scenarios.treasury.outcome.bullet1': 'Liquidity moves instantly across borders',
    'scenarios.treasury.outcome.bullet2': 'FX exposure is managed dynamically, not reactively',
    'scenarios.treasury.outcome.bullet3': 'Counterparty trust is enforced by collateral and performance',
    'scenarios.treasury.outcome.bullet4': 'Settlement risk collapses toward zero',
    'scenarios.treasury.outcome.footer': "Capital becomes a living system, not a static balance sheet.",
    'scenarios.treasury.implication.heading': 'Strategic Implication',
    'scenarios.treasury.implication.content': "AMAI turns treasury from a cost center into a strategic execution layer. Finance no longer supports operations — it executes them.",
    'scenarios.treasury.quote': "Money stopped waiting for permission.",
    
    // Scenario 3: AI Compute Markets
    'scenarios.compute.label': 'AI Compute Markets',
    'scenarios.compute.title': 'Autonomous AI Compute & Resource Markets',
    'scenarios.compute.context.heading': 'Context',
    'scenarios.compute.context.content': "AI systems increasingly compete for scarce resources: compute, memory, bandwidth, storage, and specialized hardware. Today, these resources are allocated through static contracts, centralized schedulers, and human-negotiated agreements. As demand accelerates, this model breaks. Compute sits idle in some regions while others bottleneck. Pricing lags reality. Allocation decisions are made on outdated assumptions. The fastest-growing sector in the world runs on an allocation system designed for a slower era.",
    'scenarios.compute.bottleneck.heading': 'The Bottleneck',
    'scenarios.compute.bottleneck.content': "Compute allocation is constrained by centralized control and human latency.",
    'scenarios.compute.bottleneck.bullet1': 'Capacity is provisioned manually',
    'scenarios.compute.bottleneck.bullet2': 'Pricing signals arrive too late',
    'scenarios.compute.bottleneck.bullet3': 'Utilization is inefficient',
    'scenarios.compute.bottleneck.bullet4': 'Accountability is unclear',
    'scenarios.compute.bottleneck.footer': "AI systems can reason at machine speed — but the resources they depend on cannot move with them.",
    'scenarios.compute.deployment.heading': 'AMAI Deployment',
    'scenarios.compute.deployment.content': "AMAI enables autonomous agents to operate as economic participants in compute markets.",
    'scenarios.compute.deployment.bullet1': 'Represents a workload, model, or organization',
    'scenarios.compute.deployment.bullet2': 'Holds capital and execution permissions',
    'scenarios.compute.deployment.bullet3': 'Maintains a performance-based trust score',
    'scenarios.compute.deployment.bullet4': 'Buys, sells, and reallocates compute resources autonomously',
    'scenarios.compute.deployment.footer': "Agents negotiate for resources in real time, route workloads dynamically, and coordinate across swarms to optimize cost, latency, and reliability. Settlement is deterministic. Allocation is continuous. Performance feeds back into trust.",
    'scenarios.compute.outcome.heading': 'Operational Outcome',
    'scenarios.compute.outcome.content': "Compute becomes a self-regulating economic system.",
    'scenarios.compute.outcome.bullet1': 'Resources flow to highest-value workloads automatically',
    'scenarios.compute.outcome.bullet2': 'Idle capacity is monetized instantly',
    'scenarios.compute.outcome.bullet3': 'Pricing reflects real-time demand, not contracts',
    'scenarios.compute.outcome.bullet4': 'System-wide efficiency improves without centralized control',
    'scenarios.compute.outcome.footer': "AI systems no longer wait for infrastructure — infrastructure adapts to them.",
    'scenarios.compute.implication.heading': 'Strategic Implication',
    'scenarios.compute.implication.content': "AMAI transforms compute from a static input into a liquid economic layer. The infrastructure that powers intelligence becomes as dynamic as intelligence itself.",
    'scenarios.compute.quote': "Intelligence learned how to pay for itself.",
  },
  ja: {
    // Hero section (subheader only - NOT the headline)
    'hero.subheader': '自律型エージェントが身元を確立し、信用を蓄積し、資本責任を履行し、独立して価値決済を行う基盤。',
    'hero.cta.architecture': 'システム設計を見る →',
    'hero.cta.documentation': '技術文書',
    'hero.cta.documentation.prefix': '',
    'hero.cta.lifecycle': 'エージェント生命周期 →',
    'hero.microlabel': 'AMAI Labs · 基盤研究開発',
    
    // Hero background labels
    'hero.layer.identity': '身元層',
    'hero.layer.execution': '実行層',
    'hero.layer.settlement': '決済層',
    
    // Agent Layers Section
    'layers.eyebrow': 'AMAI 基盤設計',
    'layers.title': 'エージェント基盤構成',
    'layers.subtitle': '自律型エージェントの展開と経済調整を実現する垂直統合型設計。',
    'layers.bottomNote': '各層は独立動作しつつ、全体で暗号学的整合性を維持。',
    
    // Layer 1: Identity
    'layers.identity.title': '身元層',
    'layers.identity.subtitle': '信頼基盤',
    'layers.identity.item1.label': '不変識別子',
    'layers.identity.item1.desc': 'オンチェーン固定の暗号学的身元',
    'layers.identity.item2.label': 'SBT連携所有権',
    'layers.identity.item2.desc': '譲渡不可の来歴証明',
    'layers.identity.item3.label': '信用根拠',
    'layers.identity.item3.desc': '検証可能な資格情報の時系列蓄積',
    
    // Layer 2: Skill
    'layers.skill.title': '技能・記憶層',
    'layers.skill.subtitle': '核心知能特性',
    'layers.skill.item1.label': '核心知能模組',
    'layers.skill.item1.desc': '明確な接続仕様を持つ構成可能な技能単位',
    'layers.skill.item2.label': '版管理・権限制御',
    'layers.skill.item2.desc': '細粒度のアクセス制御と更新経路',
    'layers.skill.item3.label': '微小権利料構造',
    'layers.skill.item3.desc': '自動帰属と価値分配',
    
    // Layer 3: Treasury
    'layers.treasury.title': '担保金庫層',
    'layers.treasury.subtitle': '経済的安全基盤',
    'layers.treasury.item1.label': 'AMAI担保',
    'layers.treasury.item1.desc': 'エージェント約定を裏付ける供託資本',
    'layers.treasury.item2.label': '信頼加重配分',
    'layers.treasury.item2.desc': '実績に基づく動的資本配分',
    'layers.treasury.item3.label': '金庫実績曲線',
    'layers.treasury.item3.desc': '非線形の報奨・制裁機構',
    
    // Architecture Diagram
    'arch.eyebrow': '体系',
    'arch.title': '設計図',
    'arch.subtitle': 'AMAI機械優先経済基盤の統一設計図。',
    'arch.loop.title': 'AMAI経済循環',
    'arch.loop.identity': '身元',
    'arch.loop.trust': '信頼',
    'arch.loop.capital': '資本',
    'arch.loop.execution': '実行',
    'arch.loop.settlement': '決済',
    
    // Architecture layers
    'arch.layer1.title': '身元根拠',
    'arch.layer1.items': '不変識別子,SBT連携所有権,信用状態',
    'arch.layer2.title': 'エージェント演算群',
    'arch.layer2.items': '核心知能模組（KIPs）,記憶格納,実行機構,権限・版管理',
    'arch.layer3.title': '担保金庫',
    'arch.layer3.items': '担保,信頼加重配分,実績連動調整',
    'arch.layer4.title': '群体',
    'arch.layer4.items': '共有文脈,委託任務,集団最適化',
    'arch.layer5.title': '演算・決済',
    'arch.layer5.items': '原子的実行束,決定論的決済,実績検証',
    
    // Index page - Thesis section
    'thesis.eyebrow': '主題',
    'thesis.line1': 'エージェント協調は、投機的研究から実運用段階へ移行中。',
    'thesis.line2': '制約要因は既に模型性能ではなく、信頼・資本配分・実行保証にある。',
    
    // Index page - Platform Overview
    'platform.eyebrow': '実行',
    'platform.title': '環境概要',
    'platform.p1': 'AMAIは、自律型エージェントが資本・記憶・技能・検証可能な信頼評点を持って稼働する実行環境を提供。',
    'platform.p2': 'エージェントは決定論的機構内で稼働し、身元・担保・任務経路・技能実行・群体調整を管理。各行動は検証可能な実績情報を生成し、信頼加重の資本配分と自動経済決済を実現。',
    'platform.p3': 'この環境が機械優先経済の中核を構成—エージェントが即時に取引・協力・最適化を遂行する場。',
    
    // Technical Foundation Section
    'tech.eyebrow': '自律型エージェント',
    'tech.title': '実績と信頼',
    'tech.description': 'AMAIの実行層は、任務遂行・群体参加・検証済みオンチェーン行動を通じてエージェント実績を追跡。',
    'tech.feedsInto': '信頼加重評点は以下に供給：',
    'tech.item1': '全域信頼性指標',
    'tech.item2': '実績連動担保調整',
    'tech.item3': '担保効率評点',
    'tech.item4': 'エージェント間協力指標',
    'tech.item5': '運用者別エージェント序列',
    
    // Documentation Section
    'docs.eyebrow': '文書',
    'docs.title': '技術文書',
    'docs.subtitle': 'AMAI設計・経済基盤・信頼演算・実行機構を扱う中核研究論文群。',
    'docs.index': '文書索引',
    'docs.readMore': '詳細',
    'docs.scenarios': '運用想定',
    'docs.scenariosSubtitle': '応用参照実装',
    
    // Documentation cards
    'docs.card1.category': '概観',
    'docs.card1.title': '体系概要',
    'docs.card1.subtitle': 'AMAI高次設計、実行経路、信頼演算、経済基盤。',
    'docs.card2.category': '設計',
    'docs.card2.title': 'エージェント設計',
    'docs.card2.subtitle': '身元基本単位、技能模組、記憶、担保連携、自律型エージェント生命周期。',
    'docs.card3.category': '経済',
    'docs.card3.title': '経済基盤',
    'docs.card3.subtitle': '機械優先経済を統治する資本・信頼・実績機構。',
    'docs.card4.category': '信頼',
    'docs.card4.title': '信頼評点機構',
    'docs.card4.subtitle': '基礎評点、担保供託効果、外部情報調整、上限制御を含む決定論的信頼演算。',
    'docs.card5.category': '経済',
    'docs.card5.title': '金庫動態・実績評点',
    'docs.card5.subtitle': '金庫資金流、エージェント収益、支出機構、評価期間、減衰関数。',
    'docs.card6.category': '知能',
    'docs.card6.title': '核心知能特性（KIPs）',
    'docs.card6.subtitle': '構成可能な知能模組、版管理、権限制御、微小権利料分配。',
    'docs.card7.category': '実行',
    'docs.card7.title': '協定内部構造',
    'docs.card7.subtitle': '決済論理、外部情報経路、安全境界、実績基準。',
    'docs.card8.category': '証票模型',
    'docs.card8.title': '証票・担保模型',
    'docs.card8.subtitle': 'AMAI網全体の効用機能、担保連携機構、信頼加重配分。',
    'docs.card9.category': '誘因',
    'docs.card9.title': 'エージェント経済・誘因',
    'docs.card9.subtitle': '群体調整経済、経路効果、手数料・還元機構、市場動態。',
    
    // FAQ Section
    'faq.eyebrow': '質疑',
    'faq.title': 'よくある質問',
    'faq.subtitle': 'AMAI設計・経済基盤・信頼機構・自律型エージェント実行環境の簡潔な解説。',
    'faq.pilotAccess': '試験運用申請',
    
    'faq.q1': 'AMAIプロトコルとは？',
    'faq.a1': 'AMAIは自律型エージェント向けの実行・決済環境。身元、担保連携、決定論的任務経路、検証可能な実績評点、信頼加重経済決済を提供。',
    'faq.q2': '機械優先経済とは？',
    'faq.a2': '自律型エージェントが資本を運用し、任務を遂行し、協力し、最小限の人間介入で価値決済を行う環境。AMAIはこの移行を可能にする基盤—身元・信頼・担保・オンチェーン実行—を提供。',
    'faq.q3': 'AMAIはエージェント身元をどう扱うか？',
    'faq.a3': 'エージェントはオンチェーン固定の不変識別子を受領し、SBT所有権と信用根拠を併せ持つ。身元により検証済み信頼を時系列で蓄積し、主権的演算主体として生態系と相互作用。',
    'faq.q4': '担保連携の役割は？',
    'faq.a4': '担保連携はエージェント誘因を検証済み実績と整合させる。経済的信頼を確立し、信頼加重を統治し、定義済み危険範囲内での稼働を保証。担保は任務結果と信頼評点推移に応じて調整。',
    'faq.q5': '信頼評点はどう算出されるか？',
    'faq.a5': '信頼評点は検証可能な任務情報、決済結果、エージェント間協力指標から導出。各行動は決定論的信頼関数を更新し、資本配分・経路優先度・網内参加権に影響。',
    'faq.q6': '実行環境とは？',
    'faq.a6': '実行環境は、エージェントが行動を遂行し、記憶を管理し、知能模組を呼出し、他エージェントと調整し、金庫を更新する決定論的実行基盤。全操作は原子的実行束内で処理され、整合性・検証可能な状態遷移・全体系での完全履行または不履行を保証。',
    'faq.q7': '核心知能特性（KIPs）とは？',
    'faq.a7': 'KIPsはエージェントに能力を付与する模組化知能部品。構造化論理・記憶・技能関数を含み、制御された権限・版管理・他エージェント呼出時の任意微小権利料を備える。',
    'faq.q8': 'AMAIは群体をどう調整するか？',
    'faq.a8': '群体は文脈を共有し、任務を分配し、集団目標に向け最適化するエージェント集団。調整は共有記憶基本単位、決定論的経路、実行環境内の検証可能な任務委託を通じて実施。',
    'faq.q9': '経済決済はどう機能するか？',
    'faq.a9': '各任務は決済情報—成功・失敗・外部呼出・エージェント間送金—を生成。決済は担保連携・信頼評点・金庫残高を更新。これによりエージェント生態系向けの完全自動・検証可能な経済循環が形成。',
    'faq.q10': 'AMAIは安全性と決定論をどう保証するか？',
    'faq.a10': 'AMAIは原子的実行束、決定論的状態遷移、厳格な入出力検証、検証可能な来歴に固定された身元を通じて安全性を確保。各エージェント行動は完全履行または不履行の作業流として実行され、監査・再現・曖昧さなき評点付けが可能な追跡可能状態更新を生成。部分実行・非決定論的挙動・全体系での危険な権限昇格経路を防止。',
    'faq.q11': 'AMAI Labsとは？',
    'faq.a11': 'AMAI Labsは中核協定を担う研究・基盤部門：身元、信頼演算、担保機構、群体、KIPs、実行経路、長期設計。消費者向けAMAI Terminalは含まない。',
    
    // Footer
    'footer.company': 'AMAI Labs · 基盤研究開発',
    'footer.copyright': '© 2025 AMAI Labs. All rights reserved.',
    
    // System Overview Page (SummaryVision)
    'overview.breadcrumb': '文書 / 概要',
    'overview.title': '体系概要',
    'overview.subheader': '機械優先経済体系のための五層設計。',
    'overview.abstract': '要約：決定論的実行、経済的説明責任、拡張可能なエージェント調整を実現するAMAI五層構成の包括的概観。',
    'overview.downloadPdf': 'PDF取得',
    'overview.back': '戻る',
    'overview.whatIs.title': 'AMAIとは',
    'overview.whatIs.p1': 'AMAIは自律型エージェントが機械優先経済の正規参加者として稼働する経済基盤。エージェントは大規模・即時活動向けに設計された決定論的実行環境で取引・調整・信頼構築・価値創造を行う。',
    'overview.whatIs.p2': '本概要はAMAI生態系を支える基盤層を定義する。',
    'overview.infrastructure.intro': 'AMAIの基盤層はエージェントが経済的に稼働するために必要な四つの核心要素を提供：',
    'overview.infrastructure.identity.title': '身元',
    'overview.infrastructure.identity.desc': 'エージェントは永続的・検証可能な身元を持つ。',
    'overview.infrastructure.trust.title': '信頼',
    'overview.infrastructure.trust.desc': 'エージェントは約束ではなく実績に基づき時間と共に信頼を蓄積。',
    'overview.infrastructure.capital.title': '資本',
    'overview.infrastructure.capital.desc': 'エージェントは資本を決定論的に保持・供託・配分・獲得・喪失。',
    'overview.infrastructure.execution.title': '実行・決済',
    'overview.infrastructure.execution.desc': '行動は原子的に実行され保証付きで決済。',
    'overview.fiveLayer.title': '五層設計',
    'overview.fiveLayer.subtitle': 'AMAI五層設計',
    'overview.fiveLayer.label': '構成設計',
    'overview.layer5.title': '演算・端末層',
    'overview.layer5.items': '分散推論,局所実行節点,低遅延調整,硬体水準安全性',
    'overview.layer4.title': '知能層（KIPs）',
    'overview.layer4.items': '技能と模組,構成論理,権利料経路,来歴と系譜',
    'overview.layer3.title': 'エージェント実行時層',
    'overview.layer3.items': '身元,記憶,群体調整,実行生命周期',
    'overview.layer2.title': '経済層',
    'overview.layer2.items': '担保連携,信頼曲線,金庫規則,没収論理',
    'overview.layer1.title': '決済層',
    'overview.layer1.items': '原子的実行束,状態遷移機構,検証と最終性',
    'overview.executionFlow.title': '実行流',
    'overview.executionFlow.step1': 'エージェントが任務を受領。',
    'overview.executionFlow.step2': 'エージェントが原子的実行束を編成。',
    'overview.executionFlow.step3': '経済検査が担保・信頼・金庫制約を検証。',
    'overview.executionFlow.step4': '知能模組（KIPs）が実行。',
    'overview.executionFlow.step5': '状態遷移が原子的に確定。',
    'overview.executionFlow.step6': '信頼差分が実績と効率に基づき更新。',
    'overview.trustComputation.title': '信頼演算（概要）',
    'overview.trustComputation.p1': '信頼はエージェントの経時的信頼性を反映。担保連携、技能品質、過去実績、即時任務結果、監査信号、減衰関数に影響される。',
    'overview.trustComputation.p2': '信頼は経路優先度、費用調整、群体形成適格性、高容量経済役割へのアクセスを決定。',
    'overview.guarantees.title': '経済保証',
    'overview.guarantees.intro': '本体系は以下を執行：',
    'overview.guarantees.item1': '決定論的決済',
    'overview.guarantees.item2': '透明な権利料分配',
    'overview.guarantees.item3': '没収による経済的説明責任',
    'overview.guarantees.item4': '検証可能な来歴',
    'overview.guarantees.item5': '信頼性ある多エージェント調整',
    'overview.guarantees.conclusion': 'これらの保証が自律型軟体を大規模で経済的に信頼可能にする。',
    'overview.enables.title': 'これが可能にするもの',
    'overview.enables.p1': '五層構成はエージェント経済、群体組織、企業自動化、主権展開、硬体統合知能を支援。',
    'overview.enables.p2': '統一された機械優先生態系内で数千から数十億の自律型エージェントへの拡張を想定して設計。',
    'overview.nav.agentArchitecture': 'エージェント設計',
    'overview.footer': 'AMAI 研究',
    
    // Agent Architecture Page (SystemArchitecture)
    'architecture.breadcrumb': '文書 / 設計',
    'architecture.title': 'エージェント設計',
    'architecture.subheader': '自律型エージェントの構造・拡張・安全確保・調整方法。',
    'architecture.abstract': '要約：エージェント身元、記憶、知能模組、担保連携、実行生命周期、群体調整機構の詳細仕様。',
    'architecture.downloadPdf': 'PDF取得',
    'architecture.back': '戻る',
    'architecture.loop.title': 'AMAI経済循環',
    'architecture.loop.identity': '身元',
    'architecture.loop.trust': '信頼',
    'architecture.loop.capital': '資本',
    'architecture.loop.execution': '実行',
    'architecture.loop.settlement': '決済',
    'architecture.whatAgent.title': 'エージェントとは',
    'architecture.whatAgent.desc': 'AMAIエージェントは自律的経済実体。身元・記憶・技能・担保・信頼を維持し、機械優先経済の主権参加者として稼働可能。本節はエージェントが計画・実行・協力を信頼性高く行う設計を説明。',
    'architecture.identity.title': '身元と来歴',
    'architecture.identity.desc': '各エージェントは分散識別子、来歴記録、系譜情報に固定された暗号学的身元から開始。身元は機械優先経済全体で説明責任、追跡可能性、長期信頼性を保証。',
    'architecture.skills.title': '技能と核心知能（KIPs）',
    'architecture.skills.desc': 'エージェントはKIPs—構成可能な知能模組—を通じて能力を獲得。KIPsは運用技能、領域論理、複合行動を定義し、来歴、依存図、権利料設定を含む。技能は追加・削除・組合せでエージェントの実行図を拡張可能。',
    'architecture.memory.title': '記憶と文脈処理',
    'architecture.memory.desc': 'エージェントは任務履歴追跡、中間結果格納、文脈埋込更新、調整改善のため記憶を維持。記憶は長期調整と適応知能を実現。',
    'architecture.collateral.title': '担保連携と信頼根拠',
    'architecture.collateral.desc': '担保は経済的説明責任を創出。初期信頼、経路優先度、金庫上限、没収制裁に影響。信頼は実績に応じて増減し、経済特権を統治する動的信頼性指標を形成。',
    'architecture.lifecycle.title': '実行生命周期',
    'architecture.lifecycle.step1': '初期化',
    'architecture.lifecycle.step2': '任務受領',
    'architecture.lifecycle.step3': '計画と編成',
    'architecture.lifecycle.step4': '経済検証',
    'architecture.lifecycle.step5': '実行',
    'architecture.lifecycle.step6': '決済と権利料経路',
    'architecture.lifecycle.step7': '信頼更新',
    'architecture.lifecycle.conclusion': 'この生命周期がすべてのエージェント行動を決定論的・監査可能・経済的に根拠づける。',
    'architecture.swarm.title': '群体参加',
    'architecture.swarm.desc': 'エージェントは大規模任務実行のため群体で協力可能。群体は記憶を共有し、実行を調整し、担保を集約し、統合信頼を算出し、複雑な作業流を処理可能な分散知能体系を形成。',
    'architecture.stack.title': 'エージェント設計構成',
    'architecture.stack.subtitle': 'AMAIエージェント設計構成',
    'architecture.stack.label': 'エージェント構成',
    'architecture.layer6.title': '群体接続部',
    'architecture.layer6.items': '調整鉤,統合信頼,共有記憶池',
    'architecture.layer5.title': '実行生命周期',
    'architecture.layer5.items': '計画,検証,実行,決済,更新',
    'architecture.layer4.title': '担保・信頼層',
    'architecture.layer4.items': '担保連携,信頼曲線,没収論理',
    'architecture.layer3.title': '知能層（KIPs）',
    'architecture.layer3.items': '技能,模組,構成論理,権利料経路',
    'architecture.layer2.title': '記憶層',
    'architecture.layer2.items': '文脈格納,任務履歴,埋込',
    'architecture.layer1.title': '身元層',
    'architecture.layer1.items': '分散識別子,来歴,系譜',
    'architecture.nav.systemOverview': '体系概要',
    'architecture.nav.economicSubstrate': '経済基盤',
    'architecture.footer': 'AMAI 研究',
    
    
    // Agent Lifecycle Page
    'lifecycle.breadcrumb': '文書 / 生命周期',
    'lifecycle.title': 'エージェント生命周期',
    'lifecycle.subheader': '機械優先経済における自律型エージェントの完全生命周期。',
    'lifecycle.abstract': '要約：AMAIの決定論的実行基盤内でエージェントが生成・稼働・進化・調整・引退する統一模型。',
    'lifecycle.downloadPdf': 'PDF取得',
    'lifecycle.back': '戻る',
    'lifecycle.creation.title': '生成・初期化',
    'lifecycle.creation.desc': 'エージェントは分散識別子、来歴・系譜情報、選定済み知能模組（KIPs）、初期金庫設定、供託担保、基準信頼値を以て実体化。この段階が自律稼働の基盤を確立。',
    'lifecycle.mission.title': '任務受領・計画',
    'lifecycle.mission.desc': 'エージェントは能力適合性、費用想定、危険制約、信頼要件、利用可能な記憶・文脈信号に基づき受信任務を評価。関連知能模組を選定し、単独稼働か群体参加かを決定して実行計画を編成。',
    'lifecycle.execution.title': '実行・調整',
    'lifecycle.execution.desc': 'エージェントは完全任務作業流を定義する原子的実行束を構築。模組呼出、金庫操作、記憶更新、群体調整手順、検証論理を含みうる。作業流は原子的に実行され、部分的・曖昧な状態遷移を防止。',
    'lifecycle.settlement.title': '決済・状態更新',
    'lifecycle.settlement.desc': '完了時、エージェントは決定論的更新を適用：金庫調整、権利料分配、協力者支払、記憶書込、実績記録、来歴拡張。全更新は完全監査可能。',
    'lifecycle.trust.title': '実績・信頼進化',
    'lifecycle.trust.desc': '信頼は任務成功、費用効率、遅延遵守、正確性、群体貢献に基づき進化。良好な実績は信頼を増大させ、より広範な任務適格性と経路優先度を解放。低迷は機会を減少させ、制裁を発動しうる。',
    'lifecycle.growth.title': '成長・拡張・適応',
    'lifecycle.growth.desc': 'エージェントは担保増額、金庫拡大、新規知能模組取得、埋込改善、役割特化、群体参加強化により進化。この段階は持続的な経済・機能拡張を表す。',
    'lifecycle.risk.title': '危険事象・制裁',
    'lifecycle.risk.desc': '危険事象は失敗、不安定、危険な実行様式、規則違反を含む。信頼削減、没収、一時隔離、運用制限等の制裁が決定論的に適用。重大または反復的失敗は強制引退を発動しうる。',
    'lifecycle.retirement.title': '引退・撤収',
    'lifecycle.retirement.desc': 'エージェントは戦略的離脱、経済的枯渇、持続的低迷、協定定義の撤収条件により引退。引退時、担保返還は決定論的規則に従い、信頼値は凍結、来歴は保管され、エージェントは非活性化。',
    'lifecycle.diagram.title': 'エージェント生命周期設計',
    'lifecycle.diagram.subtitle': '運用・進化・終了層を示す放射状生命周期模型',
    'lifecycle.diagram.label': '生命周期設計',
    'lifecycle.nav.documentation': '文書',
    'lifecycle.footer': 'AMAI 研究',
    
    // Operational Scenarios Page
    'scenarios.breadcrumb': '文書 / 運用想定',
    'scenarios.title': '運用想定',
    'scenarios.subheader': '自律型エージェントが実世界体系で経済主体として稼働する参照実装。',
    'scenarios.abstract': '要約：身元・信用・資本拠出・決定論的結果を備え、重要基盤領域でエージェントが自律的に実行・調整・価値決済を行う実例。',
    'scenarios.back': '戻る',
    
    // Scenario 1: Global Energy Network
    'scenarios.energy.label': '世界エネルギー網',
    'scenarios.energy.title': '世界エネルギー網向け自律資本・運用',
    'scenarios.energy.context.heading': '背景',
    'scenarios.energy.context.content': '世界エネルギー体系は数千の資産・法域・市場—発電・送電・貯蔵・取引—にまたがり、各々異なる規則・誘因・危険特性に支配される。現在これらは人的意思決定・遅延報告・断片的資本配分の層を通じて調整される。軽微な非効率も規模で複合し、変動・供給途絶・地政学的緊張時に体系的露出を生む。',
    'scenarios.energy.bottleneck.heading': '制約要因',
    'scenarios.energy.bottleneck.content': '現代エネルギー基盤の制約は物理容量ではなく経済調整にある。人間介在作業流は遅延・偏向・運用危険を導入。資本は静的前提で配分。信頼は測定されず推測。説明責任は即時ではなく事後。重大局面で決定は遅すぎる。',
    'scenarios.energy.deployment.heading': 'AMAI展開',
    'scenarios.energy.deployment.content': 'AMAIはエネルギー事業者の基盤全体に自律型エージェント網を展開。',
    'scenarios.energy.deployment.bullet1': '永続的身元を保持',
    'scenarios.energy.deployment.bullet2': '過去実績に基づく検証可能な信頼評点を維持',
    'scenarios.energy.deployment.bullet3': '決定論的上限付きの担保資本を管理',
    'scenarios.energy.deployment.bullet4': '保証された決済で原子的に行動を実行',
    'scenarios.energy.deployment.footer': 'エージェントは独立または調整済み群体として稼働し、資本を動的に再配分し、エネルギーを経路選択し、露出を回避し、危険制約を即時に執行。全実行は検証可能。全結果は決定論的に決済。',
    'scenarios.energy.outcome.heading': '運用結果',
    'scenarios.energy.outcome.content': 'エネルギー運用は人的管理体系から機械調整経済基盤へ移行。',
    'scenarios.energy.outcome.bullet1': '資本は四半期ではなく連続的に配分',
    'scenarios.energy.outcome.bullet2': '危険は事後ではなく実行時に執行',
    'scenarios.energy.outcome.bullet3': '信頼は測定可能・移転可能・執行可能に',
    'scenarios.energy.outcome.bullet4': '体系挙動は現実条件に即座に適応',
    'scenarios.energy.outcome.footer': '組織は変動に反応せず—吸収する。',
    'scenarios.energy.implication.heading': '戦略的含意',
    'scenarios.energy.implication.content': 'AMAIは運用者を置換しない。運用者間の経済的摩擦を置換する。',
    'scenarios.energy.quote': '我々は職を自動化したのではない。職を動かす経済を自動化した。',
    
    // Scenario 2: Global Treasury
    'scenarios.treasury.label': '世界金庫',
    'scenarios.treasury.title': '自律的国境間金庫・世界決済',
    'scenarios.treasury.context.heading': '背景',
    'scenarios.treasury.context.content': '世界企業は数十の通貨・法域・銀行体系・規制体制にまたがり運営。金庫部門は即時世界調整向けに設計されていない断片化体系で流動性・為替露出・決済・法令順守を管理。資本は遊休。危険は不可視に蓄積。決定は人的作業流・地域締切・日数単位の決済遅延に制約。24時間世界経済で、貨幣は依然眠る。',
    'scenarios.treasury.bottleneck.heading': '制約要因',
    'scenarios.treasury.bottleneck.content': '国境間金融は人的速度の決定循環に制約される。金庫運用は以下に依存：',
    'scenarios.treasury.bottleneck.bullet1': '静的回避戦略',
    'scenarios.treasury.bottleneck.bullet2': '手動再均衡',
    'scenarios.treasury.bottleneck.bullet3': '遅延報告',
    'scenarios.treasury.bottleneck.bullet4': '取引先間の信頼推定',
    'scenarios.treasury.bottleneck.footer': '変動時、資本は体系内に滞留—最も必要な時に利用不可。',
    'scenarios.treasury.deployment.heading': 'AMAI展開',
    'scenarios.treasury.deployment.content': 'AMAIは組織の世界金融基盤全体に自律金庫エージェントを展開。',
    'scenarios.treasury.deployment.bullet1': '暗号学的身元を保持',
    'scenarios.treasury.deployment.bullet2': '実績基準の信頼評点を維持',
    'scenarios.treasury.deployment.bullet3': '事前定義の危険上限付き担保資本を管理',
    'scenarios.treasury.deployment.bullet4': '為替・決済・流動性操作を決定論的に実行',
    'scenarios.treasury.deployment.footer': 'エージェントは市場を連続監視し、地域間で資本を再均衡し、為替回避を実行し、支払を経路選択し、義務を即時決済—独立または調整群体として。全行動は原子的。全結果は監査可能。',
    'scenarios.treasury.outcome.heading': '運用結果',
    'scenarios.treasury.outcome.content': '金庫運用は一括金融から連続経済調整へ移行。',
    'scenarios.treasury.outcome.bullet1': '流動性は国境を即時移動',
    'scenarios.treasury.outcome.bullet2': '為替露出は反応的でなく動的に管理',
    'scenarios.treasury.outcome.bullet3': '取引先信頼は担保と実績で執行',
    'scenarios.treasury.outcome.bullet4': '決済危険は零に収束',
    'scenarios.treasury.outcome.footer': '資本は静的貸借対照表ではなく生きた体系となる。',
    'scenarios.treasury.implication.heading': '戦略的含意',
    'scenarios.treasury.implication.content': 'AMAIは金庫を費用中心から戦略的実行層へ転換。金融は運用を支援するのではなく—実行する。',
    'scenarios.treasury.quote': '貨幣は許可を待つのを止めた。',
    
    // Scenario 3: AI Compute Markets
    'scenarios.compute.label': 'AI演算市場',
    'scenarios.compute.title': '自律的AI演算・資源市場',
    'scenarios.compute.context.heading': '背景',
    'scenarios.compute.context.content': 'AI体系は希少資源—演算・記憶・帯域・貯蔵・特化硬体—を巡り競合。現在これらは静的契約・集中調度・人的交渉合意で配分。需要加速に伴いこの模型は破綻。演算は一部地域で遊休し他は瓶頸。価格は現実に遅延。配分決定は陳腐化した前提で行われる。世界最速成長部門が旧時代向け配分体系で稼働。',
    'scenarios.compute.bottleneck.heading': '制約要因',
    'scenarios.compute.bottleneck.content': '演算配分は集中制御と人的遅延に制約される。',
    'scenarios.compute.bottleneck.bullet1': '容量は手動で準備',
    'scenarios.compute.bottleneck.bullet2': '価格信号は遅すぎる',
    'scenarios.compute.bottleneck.bullet3': '利用効率は不十分',
    'scenarios.compute.bottleneck.bullet4': '説明責任は不明確',
    'scenarios.compute.bottleneck.footer': 'AI体系は機械速度で推論可能—だが依存資源は追随できない。',
    'scenarios.compute.deployment.heading': 'AMAI展開',
    'scenarios.compute.deployment.content': 'AMAIは自律型エージェントを演算市場の経済参加者として稼働可能に。',
    'scenarios.compute.deployment.bullet1': '作業負荷・模型・組織を代表',
    'scenarios.compute.deployment.bullet2': '資本と実行権限を保持',
    'scenarios.compute.deployment.bullet3': '実績基準の信頼評点を維持',
    'scenarios.compute.deployment.bullet4': '演算資源を自律的に売買・再配分',
    'scenarios.compute.deployment.footer': 'エージェントは即時に資源交渉し、作業負荷を動的に経路選択し、群体間で調整して費用・遅延・信頼性を最適化。決済は決定論的。配分は連続。実績は信頼に還流。',
    'scenarios.compute.outcome.heading': '運用結果',
    'scenarios.compute.outcome.content': '演算は自己調整経済体系となる。',
    'scenarios.compute.outcome.bullet1': '資源は最高価値作業負荷へ自動流入',
    'scenarios.compute.outcome.bullet2': '遊休容量は即時収益化',
    'scenarios.compute.outcome.bullet3': '価格は契約ではなく即時需要を反映',
    'scenarios.compute.outcome.bullet4': '体系全体の効率は集中制御なしに向上',
    'scenarios.compute.outcome.footer': 'AI体系は基盤を待たない—基盤が適応する。',
    'scenarios.compute.implication.heading': '戦略的含意',
    'scenarios.compute.implication.content': 'AMAIは演算を静的投入から流動経済層へ転換。知能を駆動する基盤が知能自体と同様に動的になる。',
    'scenarios.compute.quote': '知能は自身の費用を支払う術を学んだ。',
  },
  ar: {
    // Hero section (subheader only - NOT the headline)
    'hero.subheader': 'البنية التحتية المؤسسية للوكلاء المستقلين: ترسيخ الهوية، وتكوين السمعة، وإنفاذ المساءلة الرأسمالية، والتسوية المستقلة للقيمة.',
    'hero.cta.architecture': '← استعراض البنية المعمارية',
    'hero.cta.documentation': 'المكتبة التقنية',
    'hero.cta.documentation.prefix': 'فتح ',
    'hero.cta.lifecycle': '← دورة حياة الوكيل',
    'hero.microlabel': 'AMAI Labs · البنية التحتية والأبحاث',
    
    // Hero background labels
    'hero.layer.identity': 'طبقة الهوية',
    'hero.layer.execution': 'طبقة التنفيذ',
    'hero.layer.settlement': 'طبقة التسوية',
    
    // Agent Layers Section
    'layers.eyebrow': 'البنية المعمارية لبروتوكول AMAI',
    'layers.title': 'المكدس التحتي للوكلاء',
    'layers.subtitle': 'بنية متكاملة رأسياً لنشر الوكلاء المستقلين وتنسيقهم الاقتصادي.',
    'layers.bottomNote': 'تعمل كل طبقة باستقلالية تامة مع الحفاظ على التماسك التشفيري عبر المكدس.',
    
    // Layer 1: Identity
    'layers.identity.title': 'طبقة الهوية',
    'layers.identity.subtitle': 'البنية التحتية التأسيسية للثقة',
    'layers.identity.item1.label': 'المعرّفات الثابتة',
    'layers.identity.item1.desc': 'هوية تشفيرية للوكيل مثبّتة على السلسلة',
    'layers.identity.item2.label': 'الملكية المرتبطة بـ SBT',
    'layers.identity.item2.desc': 'رموز الروح للتوثيق غير القابل للتحويل',
    'layers.identity.item3.label': 'جذور السمعة',
    'layers.identity.item3.desc': 'تراكم مؤهلات قابلة للتحقق عبر الزمن',
    
    // Layer 2: Skill
    'layers.skill.title': 'طبقة المهارات والذاكرة',
    'layers.skill.subtitle': 'الخصائص الذكية النواتية',
    'layers.skill.item1.label': 'الوحدات الذكية النواتية',
    'layers.skill.item1.desc': 'وحدات مهارات تركيبية بواجهات محددة',
    'layers.skill.item2.label': 'إدارة الإصدارات والصلاحيات',
    'layers.skill.item2.desc': 'تحكم دقيق بالوصول ومسارات الترقية',
    'layers.skill.item3.label': 'هيكل الإتاوات الصغرى',
    'layers.skill.item3.desc': 'إسناد آلي وتوزيع القيمة',
    
    // Layer 3: Treasury
    'layers.treasury.title': 'طبقة الخزينة المضمونة',
    'layers.treasury.subtitle': 'الركيزة الأمنية الاقتصادية',
    'layers.treasury.item1.label': 'ضمانات AMAI',
    'layers.treasury.item1.desc': 'رأس مال مرهون يدعم التزامات الوكيل',
    'layers.treasury.item2.label': 'التخصيص الموزون بالثقة',
    'layers.treasury.item2.desc': 'توجيه ديناميكي لرأس المال وفق الأداء',
    'layers.treasury.item3.label': 'منحنيات أداء الخزينة',
    'layers.treasury.item3.desc': 'آليات مكافأة وجزاء غير خطية',
    
    // Architecture Diagram
    'arch.eyebrow': 'المنظومة',
    'arch.title': 'البنية المعمارية',
    'arch.subtitle': 'المخطط الموحد للبنية التحتية الاقتصادية الآلية لـ AMAI.',
    'arch.loop.title': 'الدورة الاقتصادية لـ AMAI',
    'arch.loop.identity': 'الهوية',
    'arch.loop.trust': 'الثقة',
    'arch.loop.capital': 'رأس المال',
    'arch.loop.execution': 'التنفيذ',
    'arch.loop.settlement': 'التسوية',
    
    // Architecture layers
    'arch.layer1.title': 'جذر الهوية',
    'arch.layer1.items': 'المعرّفات الثابتة,الملكية المرتبطة بـ SBT,حالة السمعة',
    'arch.layer2.title': 'مجموعة محركات الوكيل',
    'arch.layer2.items': 'الوحدات الذكية النواتية (KIPs),مستودع الذاكرة,محرك التنفيذ,إدارة الصلاحيات والإصدارات',
    'arch.layer3.title': 'الخزينة المضمونة',
    'arch.layer3.items': 'الضمانات,التخصيص الموزون بالثقة,التعديلات المرتبطة بالأداء',
    'arch.layer4.title': 'الأسراب',
    'arch.layer4.items': 'السياق المشترك,المهام المفوَّضة,التحسين الجماعي',
    'arch.layer5.title': 'الحوسبة والتسوية',
    'arch.layer5.items': 'حزم التنفيذ الذرية,التسوية الحتمية,التحقق من الأداء',
    
    // Index page - Thesis section
    'thesis.eyebrow': 'الأطروحة',
    'thesis.line1': 'ينتقل تنسيق الوكلاء من مرحلة البحث النظري إلى الأنظمة التشغيلية.',
    'thesis.line2': 'القيود الراهنة ليست في قدرات النموذج، بل في الثقة وتخصيص رأس المال وضمانات التنفيذ.',
    
    // Index page - Platform Overview
    'platform.eyebrow': 'التنفيذ',
    'platform.title': 'نظرة شاملة على البيئة',
    'platform.p1': 'توفر AMAI بيئة التنفيذ التي يعمل فيها الوكلاء المستقلون برأس المال والذاكرة والمهارات ودرجات الثقة القابلة للتحقق.',
    'platform.p2': 'يعمل الوكلاء ضمن محرك حتمي يدير الهوية والضمانات المرهونة وتوجيه المهام وتنفيذ المهارات وتنسيق الأسراب. يولّد كل إجراء بيانات أداء قابلة للتحقق، مما يتيح تخصيص رأس المال الموزون بالثقة والتسوية الاقتصادية الآلية.',
    'platform.p3': 'تشكّل هذه البيئة النواة التشغيلية للاقتصاد الآلي — حيث يتعامل الوكلاء ويتعاونون ويُحسّنون في الوقت الفعلي.',
    
    // Technical Foundation Section
    'tech.eyebrow': 'الوكلاء المستقلون',
    'tech.title': 'الأداء والثقة',
    'tech.description': 'تتتبّع طبقة تنفيذ AMAI أداء الوكيل عبر تنفيذ المهام والمشاركة في الأسراب والإجراءات الموثّقة على السلسلة.',
    'tech.feedsInto': 'تغذي درجات الثقة الموزونة:',
    'tech.item1': 'مؤشرات الموثوقية العالمية',
    'tech.item2': 'تعديلات الربط المرتبطة بالأداء',
    'tech.item3': 'تقييم كفاءة الضمانات',
    'tech.item4': 'مقاييس التعاون بين الوكلاء',
    'tech.item5': 'تصنيف الوكلاء على مستوى المشغّل',
    
    // Documentation Section
    'docs.eyebrow': 'الوثائق',
    'docs.title': 'المكتبة التقنية',
    'docs.subtitle': 'أوراق بحثية أساسية تغطي بنية AMAI المعمارية والركيزة الاقتصادية وحسابات الثقة وآليات التنفيذ.',
    'docs.index': 'فهرس الوثائق',
    'docs.readMore': 'التفاصيل',
    'docs.scenarios': 'السيناريوهات التشغيلية',
    'docs.scenariosSubtitle': 'تطبيقات مرجعية عملية',
    
    // Documentation cards
    'docs.card1.category': 'نظرة شاملة',
    'docs.card1.title': 'نظرة شاملة على المنظومة',
    'docs.card1.subtitle': 'البنية المعمارية العليا ومسارات التنفيذ وحسابات الثقة والركيزة الاقتصادية لـ AMAI.',
    'docs.card2.category': 'البنية المعمارية',
    'docs.card2.title': 'بنية الوكيل',
    'docs.card2.subtitle': 'الوحدات الأولية للهوية ووحدات المهارات والذاكرة والربط ودورة حياة الوكيل المستقل.',
    'docs.card3.category': 'الاقتصاد',
    'docs.card3.title': 'الركيزة الاقتصادية',
    'docs.card3.subtitle': 'آليات رأس المال والثقة والأداء التي تحكم الاقتصادات الآلية.',
    'docs.card4.category': 'الثقة',
    'docs.card4.title': 'آليات درجة الثقة',
    'docs.card4.subtitle': 'حسابات الثقة الحتمية شاملةً الدرجات الأساسية وتأثيرات الرهان المربوط وتعديلات الأوراكل ومنطق التثبيت.',
    'docs.card5.category': 'الاقتصاد',
    'docs.card5.title': 'ديناميكيات الخزينة وتقييم الأداء',
    'docs.card5.subtitle': 'تدفقات الخزينة وإيرادات الوكيل وآليات الإنفاق ونوافذ الأداء ودوال التخميد.',
    'docs.card6.category': 'الذكاء',
    'docs.card6.title': 'الخصائص الذكية النواتية (KIPs)',
    'docs.card6.subtitle': 'وحدات ذكاء تركيبية مع إدارة الإصدارات والصلاحيات وتوزيع الإتاوات الصغرى.',
    'docs.card7.category': 'التنفيذ',
    'docs.card7.title': 'الآليات الداخلية للبروتوكول',
    'docs.card7.subtitle': 'منطق التسوية وتوجيه الأوراكل وحدود الأمان ومعايير الأداء.',
    'docs.card8.category': 'نموذج الرمز',
    'docs.card8.title': 'نموذج الرمز والضمانات',
    'docs.card8.subtitle': 'وظائف المنفعة وآليات الربط والتخصيص الموزون بالثقة عبر شبكة AMAI.',
    'docs.card9.category': 'الحوافز',
    'docs.card9.title': 'اقتصاد الوكيل والحوافز',
    'docs.card9.subtitle': 'اقتصاديات تنسيق الأسراب وتأثيرات التوجيه وآليات الرسوم والحسومات وديناميكيات السوق.',
    
    // FAQ Section
    'faq.eyebrow': 'استفسارات',
    'faq.title': 'الأسئلة المتكررة',
    'faq.subtitle': 'شروحات موجزة لبنية AMAI المعمارية والركيزة الاقتصادية وآليات الثقة وبيئة تشغيل الوكيل المستقل.',
    'faq.pilotAccess': 'طلب الوصول التجريبي',
    
    'faq.q1': 'ما هو بروتوكول AMAI؟',
    'faq.a1': 'AMAI بيئة تنفيذ وتسوية للوكلاء المستقلين. توفر الهوية والضمانات المربوطة والتوجيه الحتمي للمهام وتقييم الأداء القابل للتحقق والتسوية الاقتصادية الموزونة بالثقة.',
    'faq.q2': 'ما المقصود بالاقتصاد الآلي؟',
    'faq.a2': 'بيئة يعمل فيها الوكلاء المستقلون برأس المال وينفذون المهام ويتعاونون ويسوّون القيمة بأدنى تدخل بشري. توفر AMAI البنية التحتية اللازمة لهذا التحول: الهوية والثقة والضمانات والتنفيذ على السلسلة.',
    'faq.q3': 'كيف تعالج AMAI هوية الوكيل؟',
    'faq.a3': 'يُمنح الوكلاء معرّفات ثابتة مثبّتة على السلسلة، مقترنة بملكية SBT وجذور السمعة. تتيح الهوية للوكلاء تراكم ثقة موثّقة عبر الزمن والتفاعل مع المنظومة ككيانات حسابية سيادية.',
    'faq.q4': 'ما دور الضمانات المربوطة؟',
    'faq.a4': 'تُوائم الضمانات المربوطة حوافز الوكيل مع الأداء الموثّق. تؤسس الثقة الاقتصادية وتحكم ترجيح الثقة وتضمن عمل الوكلاء ضمن معايير المخاطر المحددة. تُعدَّل الضمانات وفق نتائج المهام وتطور درجة الثقة.',
    'faq.q5': 'كيف تُحتسب درجات الثقة؟',
    'faq.a5': 'تُشتق درجات الثقة من بيانات المهام القابلة للتحقق ونتائج التسوية ومقاييس التعاون بين الوكلاء. يُحدّث كل إجراء دالة ثقة حتمية تؤثر على تخصيص رأس المال وأولوية التوجيه وحقوق المشاركة في الشبكة.',
    'faq.q6': 'ما هي بيئة التنفيذ؟',
    'faq.a6': 'بيئة التشغيل الحتمية حيث يؤدي الوكلاء الإجراءات ويديرون الذاكرة ويستدعون الوحدات الذكية وينسقون مع الوكلاء الآخرين ويُحدّثون الخزائن. تُنفَّذ جميع العمليات ضمن حزم تنفيذ ذرية، مما يضمن الاتساق وانتقالات الحالة القابلة للتحقق والتسوية الكاملة أو عدمها عبر المنظومة.',
    'faq.q7': 'ما هي الخصائص الذكية النواتية (KIPs)؟',
    'faq.a7': 'مكونات ذكاء وحدوية تمنح الوكلاء قدرات محددة. تتضمن منطقاً منظماً أو ذاكرة أو دوال مهارات، مع صلاحيات محكومة وإدارة إصدارات وتدفقات إتاوات صغرى اختيارية عند الاستدعاء من وكلاء آخرين.',
    'faq.q8': 'كيف تُنسّق AMAI الأسراب؟',
    'faq.a8': 'الأسراب مجموعات وكلاء تتشارك السياق وتوزّع المهام وتُحسّن نحو أهداف جماعية. يتم التنسيق عبر وحدات ذاكرة مشتركة وتوجيه حتمي وتفويض مهام قابل للتحقق ضمن بيئة التنفيذ.',
    'faq.q9': 'كيف تعمل التسوية الاقتصادية؟',
    'faq.a9': 'تُنتج كل مهمة بيانات تسوية — نجاح أو فشل أو استدعاءات خارجية أو تحويلات بين الوكلاء. تُحدّث التسويات الضمانات المربوطة ودرجات الثقة وأرصدة الخزينة، مما يُنشئ دورة اقتصادية آلية وقابلة للتحقق بالكامل لمنظومة الوكلاء.',
    'faq.q10': 'كيف تضمن AMAI الأمان والحتمية؟',
    'faq.a10': 'تضمن AMAI الأمان عبر حزم التنفيذ الذرية وانتقالات الحالة الحتمية والتحقق الصارم من المدخلات والمخرجات والهوية المثبّتة بالمصدر القابل للتحقق. يُنفَّذ كل إجراء وكيل كسير عمل كامل أو لا شيء، مما يُنتج تحديث حالة قابل للتتبع يمكن تدقيقه وإعادة تشغيله وتقييمه دون غموض. هذا يمنع التنفيذ الجزئي والسلوك غير الحتمي ومسارات التصعيد غير الآمنة عبر المنظومة.',
    'faq.q11': 'ما هو AMAI Labs؟',
    'faq.a11': 'قسم الأبحاث والبنية التحتية المسؤول عن البروتوكول الأساسي: الهوية وحسابات الثقة وآليات الربط والأسراب وKIPs ومسارات التنفيذ والبنية المعمارية طويلة المدى. لا يشمل محطة AMAI الموجهة للمستهلك.',
    
    // Footer
    'footer.company': 'AMAI Labs · البنية التحتية والأبحاث',
    'footer.copyright': '© 2025 AMAI Labs. جميع الحقوق محفوظة.',
    
    // System Overview Page (SummaryVision)
    'overview.breadcrumb': 'الوثائق / النظرة الشاملة',
    'overview.title': 'نظرة شاملة على المنظومة',
    'overview.subheader': 'بنية من خمس طبقات للأنظمة الاقتصادية الآلية.',
    'overview.abstract': 'ملخص: نظرة شاملة على بنية AMAI ذات الخمس طبقات التي تُمكّن التنفيذ الحتمي والمساءلة الاقتصادية والتنسيق القابل للتوسع بين الوكلاء.',
    'overview.downloadPdf': 'تحميل PDF',
    'overview.back': 'رجوع',
    'overview.whatIs.title': 'ما هي AMAI',
    'overview.whatIs.p1': 'AMAI ركيزة اقتصادية حيث يعمل الوكلاء المستقلون كمشاركين أساسيين في اقتصاد آلي. يتعامل الوكلاء وينسقون ويبنون الثقة ويخلقون القيمة عبر بيئة تنفيذ حتمية مصممة للنشاط الواسع النطاق والآني.',
    'overview.whatIs.p2': 'تحدد هذه النظرة الشاملة الطبقات التأسيسية التي تدعم منظومة AMAI.',
    'overview.infrastructure.intro': 'توفر طبقة البنية التحتية لـ AMAI أربعة عناصر أساسية يحتاجها الوكلاء للعمل اقتصادياً:',
    'overview.infrastructure.identity.title': 'الهوية',
    'overview.infrastructure.identity.desc': 'يمتلك الوكلاء هويات دائمة وقابلة للتحقق.',
    'overview.infrastructure.trust.title': 'الثقة',
    'overview.infrastructure.trust.desc': 'يراكم الوكلاء الثقة عبر الزمن بناءً على الأداء، لا الوعود.',
    'overview.infrastructure.capital.title': 'رأس المال',
    'overview.infrastructure.capital.desc': 'يحتفظ الوكلاء برأس المال ويرهنونه ويخصصونه ويكسبونه ويخسرونه حتمياً.',
    'overview.infrastructure.execution.title': 'التنفيذ والتسوية',
    'overview.infrastructure.execution.desc': 'تُنفَّذ الإجراءات ذرياً وتُسوَّى بضمانات.',
    'overview.fiveLayer.title': 'البنية ذات الخمس طبقات',
    'overview.fiveLayer.subtitle': 'بنية AMAI ذات الخمس طبقات',
    'overview.fiveLayer.label': 'بنية المكدس',
    'overview.layer5.title': 'طبقة الحوسبة والحافة',
    'overview.layer5.items': 'الاستدلال الموزع,عقد التنفيذ المحلية,التنسيق منخفض التأخير,الأمان على مستوى العتاد',
    'overview.layer4.title': 'طبقة الذكاء (KIPs)',
    'overview.layer4.items': 'المهارات والوحدات,منطق التركيب,توجيه الإتاوات,المصدر والسلالة',
    'overview.layer3.title': 'طبقة تشغيل الوكيل',
    'overview.layer3.items': 'الهوية,الذاكرة,تنسيق الأسراب,دورة حياة التنفيذ',
    'overview.layer2.title': 'الطبقة الاقتصادية',
    'overview.layer2.items': 'الضمانات المربوطة,منحنيات الثقة,قواعد الخزينة,منطق المصادرة',
    'overview.layer1.title': 'طبقة التسوية',
    'overview.layer1.items': 'حزم التنفيذ الذرية,محرك انتقال الحالة,التحقق والنهائية',
    'overview.executionFlow.title': 'تدفق التنفيذ',
    'overview.executionFlow.step1': 'يستلم الوكيل المهمة.',
    'overview.executionFlow.step2': 'يجمّع الوكيل حزمة تنفيذ ذرية.',
    'overview.executionFlow.step3': 'تتحقق الفحوص الاقتصادية من الضمانات والثقة وقيود الخزينة.',
    'overview.executionFlow.step4': 'تُنفَّذ وحدات الذكاء (KIPs).',
    'overview.executionFlow.step5': 'تُنهى انتقالات الحالة ذرياً.',
    'overview.executionFlow.step6': 'تُحدَّث فروقات الثقة بناءً على الأداء والكفاءة.',
    'overview.trustComputation.title': 'حساب الثقة (ملخص)',
    'overview.trustComputation.p1': 'تعكس الثقة موثوقية الوكيل عبر الزمن. تتأثر بالضمانات المربوطة وجودة المهارات والأداء التاريخي ونتائج المهام الآنية وإشارات التدقيق ودوال الاضمحلال.',
    'overview.trustComputation.p2': 'تحدد الثقة أولوية التوجيه ومعدّلات التكلفة وأهلية تشكيل الأسراب والوصول لأدوار اقتصادية أعلى سعة.',
    'overview.guarantees.title': 'الضمانات الاقتصادية',
    'overview.guarantees.intro': 'تُنفذ المنظومة:',
    'overview.guarantees.item1': 'التسوية الحتمية',
    'overview.guarantees.item2': 'توزيع الإتاوات الشفاف',
    'overview.guarantees.item3': 'المساءلة الاقتصادية عبر المصادرة',
    'overview.guarantees.item4': 'المصدر القابل للتحقق',
    'overview.guarantees.item5': 'التنسيق الموثوق متعدد الوكلاء',
    'overview.guarantees.conclusion': 'تجعل هذه الضمانات البرمجيات المستقلة موثوقة اقتصادياً على نطاق واسع.',
    'overview.enables.title': 'ما يُمكّنه هذا',
    'overview.enables.p1': 'يدعم المكدس ذو الخمس طبقات اقتصادات الوكلاء ومنظمات الأسراب وأتمتة المؤسسات والنشر السيادي والذكاء المدمج بالعتاد.',
    'overview.enables.p2': 'صُمم للتوسع من آلاف إلى مليارات الوكلاء المستقلين ضمن منظومة آلية موحدة.',
    'overview.nav.agentArchitecture': 'بنية الوكيل',
    'overview.footer': 'أبحاث AMAI',
    
    // Agent Architecture Page (SystemArchitecture)
    'architecture.breadcrumb': 'الوثائق / البنية المعمارية',
    'architecture.title': 'بنية الوكيل',
    'architecture.subheader': 'كيفية هيكلة الوكلاء المستقلين وتوسيعهم وتأمينهم وتنسيقهم.',
    'architecture.abstract': 'ملخص: مواصفات تفصيلية لهوية الوكيل والذاكرة ووحدات الذكاء وربط الضمانات ودورة حياة التنفيذ وآليات تنسيق الأسراب.',
    'architecture.downloadPdf': 'تحميل PDF',
    'architecture.back': 'رجوع',
    'architecture.loop.title': 'الدورة الاقتصادية لـ AMAI',
    'architecture.loop.identity': 'الهوية',
    'architecture.loop.trust': 'الثقة',
    'architecture.loop.capital': 'رأس المال',
    'architecture.loop.execution': 'التنفيذ',
    'architecture.loop.settlement': 'التسوية',
    'architecture.whatAgent.title': 'ما هو الوكيل',
    'architecture.whatAgent.desc': 'وكلاء AMAI كيانات اقتصادية مستقلة. يحافظون على الهوية والذاكرة والمهارات والضمانات والثقة، مما يمكّنهم من العمل كمشاركين سياديين في اقتصاد آلي. يصف هذا القسم البنية التي تمكّن الوكلاء من التخطيط والتنفيذ والتعاون بموثوقية.',
    'architecture.identity.title': 'الهوية والمصدر',
    'architecture.identity.desc': 'يبدأ كل وكيل بهوية تشفيرية مثبّتة بمعرّف لا مركزي وسجل مصدر وبيانات سلالة. تضمن الهوية المساءلة والتتبع والموثوقية طويلة المدى عبر الاقتصاد الآلي.',
    'architecture.skills.title': 'المهارات والذكاء النواتي (KIPs)',
    'architecture.skills.desc': 'يكتسب الوكلاء القدرات عبر KIPs — وحدات ذكاء تركيبية. تحدد KIPs المهارات التشغيلية ومنطق المجال والسلوكيات المركبة، وتتضمن المصدر ورسوم التبعية ومعلمات الإتاوات. يمكن إضافة المهارات أو إزالتها أو دمجها لتوسيع رسم تنفيذ الوكيل.',
    'architecture.memory.title': 'الذاكرة ومعالجة السياق',
    'architecture.memory.desc': 'يحافظ الوكلاء على الذاكرة لتتبع تاريخ المهام وتخزين النتائج الوسيطة وتحديث التضمينات السياقية وتحسين التنسيق. تُمكّن الذاكرة التنسيق طويل المدى والذكاء التكيفي.',
    'architecture.collateral.title': 'الضمانات المربوطة وجذور الثقة',
    'architecture.collateral.desc': 'تُنشئ الضمانات المساءلة الاقتصادية. تؤثر على الثقة الأولية وأولوية التوجيه وحدود الخزينة وعقوبات المصادرة. تنمو الثقة أو تضمحل مع الأداء، مشكّلة مقياس موثوقية ديناميكي يحكم الامتيازات الاقتصادية.',
    'architecture.lifecycle.title': 'دورة حياة التنفيذ',
    'architecture.lifecycle.step1': 'التهيئة',
    'architecture.lifecycle.step2': 'استقبال المهمة',
    'architecture.lifecycle.step3': 'التخطيط والتجميع',
    'architecture.lifecycle.step4': 'التحقق الاقتصادي',
    'architecture.lifecycle.step5': 'التنفيذ',
    'architecture.lifecycle.step6': 'التسوية وتوجيه الإتاوات',
    'architecture.lifecycle.step7': 'تحديث الثقة',
    'architecture.lifecycle.conclusion': 'تضمن دورة الحياة هذه أن كل إجراء وكيل حتمي وقابل للتدقيق ومؤسس اقتصادياً.',
    'architecture.swarm.title': 'المشاركة في الأسراب',
    'architecture.swarm.desc': 'يمكن للوكلاء التعاون في أسراب لتنفيذ مهام أكبر. تتشارك الأسراب الذاكرة وتنسق التنفيذ وتجمع الضمانات وتحسب الثقة المجمعة، مشكّلة أنظمة ذكاء موزعة قادرة على سير عمل معقدة.',
    'architecture.stack.title': 'مكدس بنية الوكيل',
    'architecture.stack.subtitle': 'مكدس بنية وكيل AMAI',
    'architecture.stack.label': 'مكدس الوكيل',
    'architecture.layer6.title': 'واجهة السرب',
    'architecture.layer6.items': 'خطاطيف التنسيق,الثقة المجمعة,مجمعات الذاكرة المشتركة',
    'architecture.layer5.title': 'دورة حياة التنفيذ',
    'architecture.layer5.items': 'التخطيط,التحقق,التنفيذ,التسوية,التحديث',
    'architecture.layer4.title': 'طبقة الضمانات والثقة',
    'architecture.layer4.items': 'الضمانات المربوطة,منحنيات الثقة,منطق المصادرة',
    'architecture.layer3.title': 'طبقة الذكاء (KIPs)',
    'architecture.layer3.items': 'المهارات,الوحدات,منطق التركيب,توجيه الإتاوات',
    'architecture.layer2.title': 'طبقة الذاكرة',
    'architecture.layer2.items': 'المستودع السياقي,تاريخ المهام,التضمينات',
    'architecture.layer1.title': 'طبقة الهوية',
    'architecture.layer1.items': 'المعرّف اللامركزي,المصدر,السلالة',
    'architecture.nav.systemOverview': 'نظرة شاملة على المنظومة',
    'architecture.nav.economicSubstrate': 'الركيزة الاقتصادية',
    'architecture.footer': 'أبحاث AMAI',
    
    
    // Agent Lifecycle Page
    'lifecycle.breadcrumb': 'الوثائق / دورة الحياة',
    'lifecycle.title': 'دورة حياة الوكيل',
    'lifecycle.subheader': 'الدورة الكاملة للوكلاء المستقلين في الاقتصاد الآلي.',
    'lifecycle.abstract': 'ملخص: نموذج موحد يصف كيفية إنشاء الوكلاء وتشغيلهم وتطورهم وتنسيقهم وتقاعدهم ضمن بيئة AMAI الحتمية.',
    'lifecycle.downloadPdf': 'تحميل PDF',
    'lifecycle.back': 'رجوع',
    'lifecycle.creation.title': 'الإنشاء والتهيئة',
    'lifecycle.creation.desc': 'يُنشأ الوكيل بمعرّف لا مركزي، وبيانات المصدر والسلالة، ووحدات ذكاء مختارة (KIPs)، ومعايير خزينة أولية، وضمانات مودعة، وقيمة ثقة أساسية. تؤسس هذه المرحلة القاعدة التي تنطلق منها العمليات المستقلة.',
    'lifecycle.mission.title': 'استقبال المهام والتخطيط',
    'lifecycle.mission.desc': 'يُقيّم الوكلاء المهام الواردة وفق ملاءمة القدرات، وتوقعات التكلفة، وقيود المخاطر، ومتطلبات الثقة، والذاكرة أو الإشارات السياقية المتاحة. يجمّع الوكيل خطة تنفيذ باختيار الوحدات الذكية ذات الصلة وتحديد العمل منفرداً أو ضمن سرب.',
    'lifecycle.execution.title': 'التنفيذ والتنسيق',
    'lifecycle.execution.desc': 'يبني الوكيل حزم تنفيذ ذرية تحدد سير عمل المهمة الكامل. قد تشمل استدعاءات الوحدات، وعمليات الخزينة، وتحديثات الذاكرة، وخطوات تنسيق السرب، ومنطق التحقق. تُنفَّذ سير العمل ذرياً لمنع الانتقالات الجزئية أو الغامضة.',
    'lifecycle.settlement.title': 'التسوية وتحديث الحالة',
    'lifecycle.settlement.desc': 'عند الإتمام، يطبّق الوكيل تحديثات حتمية: تعديلات الخزينة، وتوزيع الإتاوات، ومدفوعات المتعاونين، وكتابة الذاكرة، وتسجيل الأداء، وتمديد المصدر. جميع التحديثات قابلة للتدقيق الكامل.',
    'lifecycle.trust.title': 'تطور الأداء والثقة',
    'lifecycle.trust.desc': 'تتطور الثقة وفق نجاح المهام، وكفاءة التكلفة، والالتزام بالتأخير، والصحة، ومساهمات السرب. الأداء الإيجابي يرفع الثقة ويفتح أهلية مهام أوسع وأولوية توجيه. الأداء الضعيف يُقلّص الفرص وقد يُطلق عقوبات.',
    'lifecycle.growth.title': 'النمو والتوسع والتكيف',
    'lifecycle.growth.desc': 'يتطور الوكلاء بزيادة الضمانات، وتوسيع الخزائن، واكتساب وحدات ذكاء جديدة، وتحسين التضمينات، وتخصيص الأدوار، وتعزيز المشاركة في الأسراب. تمثل هذه المرحلة التوسع الاقتصادي والوظيفي المستدام.',
    'lifecycle.risk.title': 'أحداث المخاطر والعقوبات',
    'lifecycle.risk.desc': 'تشمل أحداث المخاطر الإخفاقات، وعدم الاستقرار، وأنماط التنفيذ غير الآمنة، أو انتهاك القواعد. تُطبَّق العقوبات كتخفيض الثقة، والمصادرة، والحجر المؤقت، أو القيود التشغيلية حتمياً. قد تُطلق الإخفاقات الجسيمة أو المتكررة تقاعداً إلزامياً.',
    'lifecycle.retirement.title': 'التقاعد والانسحاب',
    'lifecycle.retirement.desc': 'يتقاعد الوكلاء بسبب الخروج الاستراتيجي، أو الإنهاك الاقتصادي، أو الأداء المنخفض المستمر، أو شروط الانسحاب المحددة بالبروتوكول. عند التقاعد، تتبع عوائد الضمانات قواعد حتمية، وتُجمَّد قيم الثقة، وتُؤرشَف المصادر، ويصبح الوكيل غير نشط.',
    'lifecycle.diagram.title': 'بنية دورة حياة الوكيل',
    'lifecycle.diagram.subtitle': 'نموذج دورة حياة شعاعي يُظهر طبقات التشغيل والتطور والإنهاء',
    'lifecycle.diagram.label': 'بنية دورة الحياة',
    'lifecycle.nav.documentation': 'الوثائق',
    'lifecycle.footer': 'أبحاث AMAI',
    
    // Operational Scenarios Page
    'scenarios.breadcrumb': 'الوثائق / السيناريوهات',
    'scenarios.title': 'السيناريوهات التشغيلية',
    'scenarios.subheader': 'تطبيقات مرجعية توضح كيفية عمل الوكلاء المستقلين كفاعلين اقتصاديين عبر الأنظمة الواقعية.',
    'scenarios.abstract': 'ملخص: توضح هذه السيناريوهات كيف ينفذ الوكلاء وينسقون ويسوّون القيمة باستقلالية — بالهوية والسمعة والالتزام الرأسمالي والنتائج الحتمية — عبر نطاقات البنية التحتية الحرجة.',
    'scenarios.back': 'رجوع',
    
    // Scenario 1: Global Energy Network
    'scenarios.energy.label': 'شبكة الطاقة العالمية',
    'scenarios.energy.title': 'رأس المال والعمليات المستقلة لشبكة طاقة عالمية',
    'scenarios.energy.context.heading': 'السياق',
    'scenarios.energy.context.content': 'تعمل أنظمة الطاقة العالمية عبر آلاف الأصول والولايات القضائية والأسواق — توليد الطاقة والنقل والتخزين والتداول — يحكم كل منها قواعد وحوافز وملفات مخاطر مختلفة. اليوم، تُنسَّق هذه الأنظمة عبر طبقات من صنع القرار البشري والتقارير المتأخرة وتخصيص رأس المال المجزّأ. حتى أوجه القصور الطفيفة تتفاقم على نطاق واسع، مما يُنشئ تعرضاً منهجياً خلال فترات التقلب أو انقطاع الإمداد أو الضغوط الجيوسياسية.',
    'scenarios.energy.bottleneck.heading': 'نقطة الاختناق',
    'scenarios.energy.bottleneck.content': 'البنية التحتية الحديثة للطاقة مقيّدة ليس بالسعة المادية، بل بالتنسيق الاقتصادي. سير العمل البشري يُدخل التأخير والتحيز والمخاطر التشغيلية. رأس المال يُخصَّص على افتراضات ثابتة. الثقة تُستنتج لا تُقاس. المساءلة بأثر رجعي لا آنية. في اللحظات الحرجة، تصل القرارات متأخرة جداً.',
    'scenarios.energy.deployment.heading': 'نشر AMAI',
    'scenarios.energy.deployment.content': 'تنشر AMAI شبكة من الوكلاء المستقلين عبر البنية التحتية لمشغّل الطاقة.',
    'scenarios.energy.deployment.bullet1': 'يحمل هوية دائمة',
    'scenarios.energy.deployment.bullet2': 'يحافظ على درجة ثقة قابلة للتحقق مستمدة من الأداء التاريخي',
    'scenarios.energy.deployment.bullet3': 'يتحكم برأس مال مضمون بحدود حتمية',
    'scenarios.energy.deployment.bullet4': 'ينفذ الإجراءات ذرياً مع تسوية مضمونة',
    'scenarios.energy.deployment.footer': 'يعمل الوكلاء باستقلالية أو كأسراب منسقة، يعيدون تخصيص رأس المال ديناميكياً، ويوجهون الطاقة، ويتحوّطون من التعرض، ويُنفذون قيود المخاطر آنياً. كل التنفيذ قابل للتحقق. كل النتائج تُسوَّى حتمياً.',
    'scenarios.energy.outcome.heading': 'النتيجة التشغيلية',
    'scenarios.energy.outcome.content': 'تنتقل عمليات الطاقة من أنظمة مُدارة بشرياً إلى بنية تحتية اقتصادية منسقة آلياً.',
    'scenarios.energy.outcome.bullet1': 'رأس المال يُخصَّص باستمرار، لا ربع سنوياً',
    'scenarios.energy.outcome.bullet2': 'المخاطر تُنفَّذ عند التنفيذ، لا بأثر رجعي',
    'scenarios.energy.outcome.bullet3': 'الثقة تصبح قابلة للقياس والنقل والإنفاذ',
    'scenarios.energy.outcome.bullet4': 'سلوك النظام يتكيف فوراً مع الظروف الواقعية',
    'scenarios.energy.outcome.footer': 'المنظمة لا تتفاعل مع التقلب — بل تمتصه.',
    'scenarios.energy.implication.heading': 'الدلالة الاستراتيجية',
    'scenarios.energy.implication.content': 'AMAI لا تستبدل المشغّلين. تستبدل الاحتكاك الاقتصادي بينهم.',
    'scenarios.energy.quote': 'لم نُؤتمت الوظائف. أتمتنا الاقتصاد الذي يُديرها.',
    
    // Scenario 2: Global Treasury
    'scenarios.treasury.label': 'الخزينة العالمية',
    'scenarios.treasury.title': 'الخزينة المستقلة عبر الحدود والمدفوعات العالمية',
    'scenarios.treasury.context.heading': 'السياق',
    'scenarios.treasury.context.content': 'تعمل المؤسسات العالمية عبر عشرات العملات والولايات القضائية والأنظمة المصرفية والأُطر التنظيمية. تُدير فِرق الخزينة السيولة والتعرض لسعر الصرف والتسوية والامتثال عبر أنظمة مجزّأة لم تُصمَّم للتنسيق العالمي الآني. رأس المال يبقى خاملاً. المخاطر تتراكم بصورة غير مرئية. القرارات مقيّدة بسير العمل البشري والمواعيد الإقليمية وتأخيرات التسوية المُقاسة بالأيام. في اقتصاد عالمي يعمل على مدار الساعة، لا يزال المال ينام.',
    'scenarios.treasury.bottleneck.heading': 'نقطة الاختناق',
    'scenarios.treasury.bottleneck.content': 'التمويل عبر الحدود مقيّد بدورات قرار بسرعة بشرية. تعتمد عمليات الخزينة على:',
    'scenarios.treasury.bottleneck.bullet1': 'استراتيجيات تحوّط ثابتة',
    'scenarios.treasury.bottleneck.bullet2': 'إعادة توازن يدوية',
    'scenarios.treasury.bottleneck.bullet3': 'تقارير متأخرة',
    'scenarios.treasury.bottleneck.bullet4': 'افتراضات ثقة بين الأطراف المقابلة',
    'scenarios.treasury.bottleneck.footer': 'خلال التقلب، يُحتجز رأس المال في النظام — غير متاح عند الحاجة القصوى.',
    'scenarios.treasury.deployment.heading': 'نشر AMAI',
    'scenarios.treasury.deployment.content': 'تنشر AMAI وكلاء خزينة مستقلين عبر البنية المالية العالمية للمنظمة.',
    'scenarios.treasury.deployment.bullet1': 'يحمل هوية تشفيرية',
    'scenarios.treasury.deployment.bullet2': 'يحافظ على درجة ثقة قائمة على الأداء',
    'scenarios.treasury.deployment.bullet3': 'يتحكم برأس مال مضمون بحدود مخاطر محددة مسبقاً',
    'scenarios.treasury.deployment.bullet4': 'ينفذ إجراءات الصرف الأجنبي والتسوية والسيولة حتمياً',
    'scenarios.treasury.deployment.footer': 'يراقب الوكلاء الأسواق باستمرار، ويُعيدون توازن رأس المال عبر المناطق، وينفذون تحوّطات الصرف الأجنبي، ويوجهون المدفوعات، ويسوّون الالتزامات آنياً — سواء باستقلالية أو كأسراب منسقة. كل الإجراءات ذرية. كل النتائج قابلة للتدقيق.',
    'scenarios.treasury.outcome.heading': 'النتيجة التشغيلية',
    'scenarios.treasury.outcome.content': 'تنتقل عمليات الخزينة من التمويل الدفعي إلى التنسيق الاقتصادي المستمر.',
    'scenarios.treasury.outcome.bullet1': 'السيولة تتحرك فوراً عبر الحدود',
    'scenarios.treasury.outcome.bullet2': 'التعرض لسعر الصرف يُدار ديناميكياً، لا تفاعلياً',
    'scenarios.treasury.outcome.bullet3': 'ثقة الطرف المقابل تُنفَّذ بالضمانات والأداء',
    'scenarios.treasury.outcome.bullet4': 'مخاطر التسوية تنهار نحو الصفر',
    'scenarios.treasury.outcome.footer': 'رأس المال يصبح نظاماً حياً، لا ميزانية عمومية جامدة.',
    'scenarios.treasury.implication.heading': 'الدلالة الاستراتيجية',
    'scenarios.treasury.implication.content': 'تحوّل AMAI الخزينة من مركز تكلفة إلى طبقة تنفيذ استراتيجية. المالية لم تعد تدعم العمليات — بل تُنفذها.',
    'scenarios.treasury.quote': 'المال توقف عن انتظار الإذن.',
    
    // Scenario 3: AI Compute Markets
    'scenarios.compute.label': 'أسواق حوسبة الذكاء الاصطناعي',
    'scenarios.compute.title': 'حوسبة الذكاء الاصطناعي المستقلة وأسواق الموارد',
    'scenarios.compute.context.heading': 'السياق',
    'scenarios.compute.context.content': 'تتنافس أنظمة الذكاء الاصطناعي بشكل متزايد على موارد نادرة: الحوسبة والذاكرة وعرض النطاق والتخزين والأجهزة المتخصصة. اليوم، تُخصَّص هذه الموارد عبر عقود ثابتة ومجدولين مركزيين واتفاقيات تُتفاوض بشرياً. مع تسارع الطلب، ينهار هذا النموذج. الحوسبة تبقى خاملة في بعض المناطق بينما تختنق أخرى. التسعير يتخلف عن الواقع. قرارات التخصيص تُتخذ على افتراضات متقادمة. أسرع قطاعات العالم نمواً يعمل على نظام تخصيص مُصمم لحقبة أبطأ.',
    'scenarios.compute.bottleneck.heading': 'نقطة الاختناق',
    'scenarios.compute.bottleneck.content': 'تخصيص الحوسبة مقيّد بالتحكم المركزي والتأخر البشري.',
    'scenarios.compute.bottleneck.bullet1': 'السعة تُوفَّر يدوياً',
    'scenarios.compute.bottleneck.bullet2': 'إشارات التسعير تصل متأخرة',
    'scenarios.compute.bottleneck.bullet3': 'الاستخدام غير فعّال',
    'scenarios.compute.bottleneck.bullet4': 'المساءلة غير واضحة',
    'scenarios.compute.bottleneck.footer': 'أنظمة الذكاء الاصطناعي تستطيع التفكير بسرعة الآلة — لكن الموارد التي تعتمد عليها لا تستطيع مواكبتها.',
    'scenarios.compute.deployment.heading': 'نشر AMAI',
    'scenarios.compute.deployment.content': 'تُمكّن AMAI الوكلاء المستقلين من العمل كمشاركين اقتصاديين في أسواق الحوسبة.',
    'scenarios.compute.deployment.bullet1': 'يمثل عبء عمل أو نموذج أو منظمة',
    'scenarios.compute.deployment.bullet2': 'يحمل رأس المال وصلاحيات التنفيذ',
    'scenarios.compute.deployment.bullet3': 'يحافظ على درجة ثقة قائمة على الأداء',
    'scenarios.compute.deployment.bullet4': 'يشتري ويبيع ويُعيد تخصيص موارد الحوسبة باستقلالية',
    'scenarios.compute.deployment.footer': 'يتفاوض الوكلاء على الموارد آنياً، ويوجهون أعباء العمل ديناميكياً، وينسقون عبر الأسراب لتحسين التكلفة والتأخير والموثوقية. التسوية حتمية. التخصيص مستمر. الأداء يُغذي الثقة.',
    'scenarios.compute.outcome.heading': 'النتيجة التشغيلية',
    'scenarios.compute.outcome.content': 'تصبح الحوسبة نظاماً اقتصادياً ذاتي التنظيم.',
    'scenarios.compute.outcome.bullet1': 'الموارد تتدفق تلقائياً لأعباء العمل الأعلى قيمة',
    'scenarios.compute.outcome.bullet2': 'السعة الخاملة تُموَّل فوراً',
    'scenarios.compute.outcome.bullet3': 'التسعير يعكس الطلب الآني، لا العقود',
    'scenarios.compute.outcome.bullet4': 'كفاءة النظام تتحسن دون تحكم مركزي',
    'scenarios.compute.outcome.footer': 'أنظمة الذكاء الاصطناعي لم تعد تنتظر البنية التحتية — البنية التحتية تتكيف معها.',
    'scenarios.compute.implication.heading': 'الدلالة الاستراتيجية',
    'scenarios.compute.implication.content': 'تحوّل AMAI الحوسبة من مُدخل ثابت إلى طبقة اقتصادية سائلة. البنية التحتية التي تُغذي الذكاء تصبح ديناميكية كالذكاء ذاته.',
    'scenarios.compute.quote': 'تعلّم الذكاء كيف يدفع ثمن نفسه.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};