// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-documentation.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var DOCS = [
  { slug: "system-overview", title: "System Overview \u2014 five-layer architecture" },
  { slug: "agent-architecture", title: "Agent Architecture \u2014 identity, skills, memory, lifecycle" },
  { slug: "economic-substrate", title: "Economic Substrate \u2014 capital, trust, performance" },
  { slug: "trust-mechanics", title: "Trust Mechanics \u2014 deterministic trust computation" },
  { slug: "treasury-dynamics", title: "Treasury Dynamics \u2014 flows, earnings, performance" },
  { slug: "kips", title: "KIPs \u2014 Kernelized Intelligence Properties" },
  { slug: "protocol-internals", title: "Protocol Internals \u2014 settlement + security" },
  { slug: "token-model", title: "Token Model \u2014 utility, bonding, collateral" },
  { slug: "agent-economy", title: "Agent Economy \u2014 swarm coordination and markets" },
  { slug: "agent-lifecycle", title: "Agent Lifecycle \u2014 creation, scaling, retirement" },
  { slug: "terminal", title: "Terminal \u2014 AMAI Terminal v2.0 Fiduciary Command Center" },
  { slug: "faq", title: "FAQ" },
  { slug: "roadmap", title: "Roadmap" },
  { slug: "scenarios", title: "Operational Scenarios" }
];
var list_documentation_default = defineTool({
  name: "list_documentation",
  title: "List AMAI documentation",
  description: "List every AMAI Labs documentation page available via MCP. Returns slugs to pass to get_documentation.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: DOCS.map((d) => `- ${d.slug}: ${d.title}`).join("\n") }],
    structuredContent: { docs: DOCS }
  })
});

// src/lib/mcp/tools/get-documentation.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var ALLOWED = /* @__PURE__ */ new Set([
  "system-overview",
  "agent-architecture",
  "economic-substrate",
  "trust-mechanics",
  "treasury-dynamics",
  "kips",
  "protocol-internals",
  "token-model",
  "agent-economy",
  "agent-lifecycle",
  "terminal",
  "faq",
  "roadmap",
  "scenarios"
]);
var SITE = "https://amai-insights.lovable.app";
var get_documentation_default = defineTool2({
  name: "get_documentation",
  title: "Get AMAI documentation page",
  description: "Fetch the full markdown body of a single AMAI Labs documentation page by slug (see list_documentation).",
  inputSchema: {
    slug: z.string().min(1).describe("Documentation slug, e.g. 'system-overview' or 'trust-mechanics'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ slug }) => {
    if (!ALLOWED.has(slug)) {
      return {
        content: [
          { type: "text", text: `Unknown slug '${slug}'. Call list_documentation for valid slugs.` }
        ],
        isError: true
      };
    }
    const url = `${SITE}/llms/${slug}.md`;
    const res = await fetch(url);
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch ${url}: ${res.status} ${res.statusText}` }],
        isError: true
      };
    }
    const text = await res.text();
    return {
      content: [{ type: "text", text }],
      structuredContent: { slug, url, markdown: text }
    };
  }
});

// src/lib/mcp/tools/get-full-context.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var URL = "https://amai-insights.lovable.app/llms-full.txt";
var get_full_context_default = defineTool3({
  name: "get_full_context",
  title: "Get full AMAI context",
  description: "Fetch the combined AMAI Labs documentation corpus (llms-full.txt) as a single markdown blob for full-context loading.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async () => {
    const res = await fetch(URL);
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Failed to fetch ${URL}: ${res.status} ${res.statusText}` }],
        isError: true
      };
    }
    const text = await res.text();
    return {
      content: [{ type: "text", text }],
      structuredContent: { url: URL, markdown: text }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "amai-insights-mcp",
  title: "AMAI Labs Insights",
  version: "0.1.0",
  instructions: "Read-only access to AMAI Labs documentation on the Insurance Layer for the Agentic Web (system architecture, trust mechanics, treasury dynamics, token model, KIPs, protocol internals, agent lifecycle, and more). Start with list_documentation, fetch pages with get_documentation, or pull the whole corpus with get_full_context.",
  tools: [list_documentation_default, get_documentation_default, get_full_context_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
